### ISSUE TITLE
Environments -- feature request

### ISSUE THREAD

**Issue by ivankovnatsky** [env0/terraform-provider-env0#123]
Hey guys, thanks for nice tool to automate infra pipelines. I'm wondering if there's some kind of a roadmap for provider.

Particularly I'm interested in environments, we have lots of them and it feels a bit of a mess, each one of them are created manually. If I missed something please point me. But I think there's no way to configure them in env0.

Thanks.

**Comment by omry-hay** [comment]
Hi @ivankovnatsky Thanks for the feedback.
Can you please elaborate a bit more on the use case here.
Would you like the ability to create environments with the TF provider? Or also deploy an environment?
Or maybe you only need it as a data?

**Comment by ivankovnatsky** [comment]
@omry-hay beforehand I want to say that I'm new to env0, so please let me know if the workflow is weird to what env0 was designed to be used.

we're having say multiple templates (in each we would configure different directories tf to execute the code in). currently we're using workspace-based env split (terraform workspaces), and in every other environment we choose workspace name (again all this is done manually) to run.

it feels like the environments are more of a moving parts, and i'm not 100% sure that declarative approach would be the best here, but still configuring it all manually feels tedious and unpleasant, at least for me.

>  Would you like the ability to create environments with the TF provider? Or also deploy an environment?
i think the expected workflow would be: if i create an environment using a template it should be copy the behavior of button "Run Now" (with the possibilities to choose options in between)

basically to be able to "activate" environment i think would be great.

removing environment would make it inactive.

something like this:

```terraform
data "env0_project" "default_project" {
  name = "Default Organization Project"
}

resource "env0_template" "example" {
  name        = "example"
  description = "Example template"
  repository  = "https://github.com/env0/templates"
  path        = "aws/hello-world"
}

resource "env0_template_project_assignment" "assignment" {
  template_id = env0_template.example.id
  project_id  = data.env0_project.default_project.id
}

resource "env0_environment" "this" {
  project_id = data.env0_project.default_project.id
  template_id = env0_template.example.id

  name = "env name"
  workspace_name = "workspace name"
  revision = "123sdf"

  redeploy_on_push = true
  run_on_prs = true

  approve_plan_automatically = false
}
```

--

for me personally env0 looks a bit of a complication, probably just because i accustomed to gitlab pipelines, and we were running infra pipelines there as well, and it looked like we had much more control there or some sort of flexibility. i mean probably because of my already adopted workflow i want these bells and whistles :smile:

**Comment by ivankovnatsky** [comment]
I see that there's an api for environments: https://docs.env0.com/reference#environments-1, which is cool, meaning that implementing in tf would not be such a big deal, I guess.

**Comment by omry-hay** [comment]
Hi @ivankovnatsky,

Indeed we have an API for the environments, however it's a bit more complicated as environments are created only when you deploy them for the first time, so we will need some kind of logic for this.
In addition there is no way to delete an environment, only destroy it or mark it as inactive.
Overall an environment in env0 is not really fits a terraform resource without some adjustments and conditions.
However, we are going to implement it as a `data` resource and in the future as a Terraform resource as well.

Thanks

**Comment by matthewhembree** [comment]
Having a `data env0_environment` would be good. 

I took a break from the project that I was working on, so I am a little out of sync... IIRC, it's because I need a means to resolve the environment's ID, so that I can pass it to the `environment_id` parameter. I took a break from the project that I was working on, but I have some code with comments that might explain my intentions:

```hcl
resource "env0_configuration_variable" "service_api_token" {
  name         = "service_api_token"
  value        = var.service_api_token
  is_sensitive = true
  type         = "terraform"
  project_id   = data.env0_project.service.id # Attaching to project, because there is no env0_environment.
}
```

This was from `0.0.2`.

**Comment by eranelbaz** [comment]
Hey @matthewhembree + @ivankovnatsky !
We released new version of our tf provider yesterday (v0.0.21) with environment support
examples - 
```  
data "env0_template" "example" {
  name = "Template Name"
}

data "env0_project" "default_project" {
  name = "Default Organization Project"
}

resource "env0_environment" "example" {
  name        = "environment"
  project_id  = data.env0_project.default_project.id
  template_id = data.env0_template.example.id
}

data "env0_environment" "by_id" {
  id   =  "some_id"
}

data "env0_environment" "by_name" {
  name   =  "best-env"
}
```

Currently closing this issue
Let us know if you have any more suggestions!
