### ISSUE TITLE
Template: Add posibility to use/reference git token added in organization 

### ISSUE THREAD

**Issue by ivankovnatsky** [env0/terraform-provider-env0#125]
i understand that currently there's only option for vcs when creating a template in terraform to use: "Other VCS".

however when new template is created, it's not usable, since the repo does not have access to git (please correct me if i'm wrong). at least i did not find an option here: 

https://registry.terraform.io/providers/env0/env0/latest/docs/resources/template

meaning i would have to go ahead and add one myself.

**Comment by yaronya** [comment]
Thanks for the feedback! We're planning on adding such support soon. Please follow the relevant issue: #148 
Closing this one as duplicate.
