### ISSUE TITLE
Missing `terraform import` capability for some of the resources

### ISSUE THREAD

**Issue by omry-hay** [env0/terraform-provider-env0#146]
Here is a list of resources that doesn't support `terraform import`:

1. `env0_cloud_credentials_project_assignment`
2. `env0_team`
3. `env0_team_project_assignment`
4. `env0_template_project_assignment`

**Comment by TomerHeber** [comment]
env0_team is already implemented (see #241).

**Comment by TomerHeber** [comment]
Deferring assignment imports.
If assignments are requested, may be re-opened.
