### ISSUE TITLE
project resource doesn't accept description

### ISSUE THREAD

**Issue by mmclane** [env0/terraform-provider-env0#147]
I am trying to use this provider for the first time.  I am trying to create a env0 project using this example: https://registry.terraform.io/providers/env0/env0/latest/docs/resources/project

Here is my code:
`
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
      version = "0.0.2"
    }
  }
}

provider "env0" {}

resource "env0_project" "project" {
  name        = "m3dev"
  description = "A project for Matt to dev with"
}
`

terraform init runs successfully but terraform plan gives me and error.

│ Error: Unsupported argument
│ 
│   on main.tf line 14, in resource "env0_project" "project":
│   14:   description = "A project for Matt to dev with"
│ 
│ An argument named "description" is not expected here.

If I comment out the description line I am able to successfully run a plan.

**Comment by mmclane** [comment]
Yeah, I just did exactly that.  It is working with the latest version.  Its just that the examples refer to 0.0.2 and not latest.

**Comment by razbensimon** [comment]
Fixed the docs. Thanks for your feedback!
