### ISSUE TITLE
Add support for git token resource

### ISSUE THREAD

**Issue by mmclane** [env0/terraform-provider-env0#148]
I would like to use github token_ids in my templates instead of just ssh keys.  There doesn't seem to be a data source to look up the token_id of a github token in env0 like there is for ssh keys.  Can that get added please?

**Comment by omry-hay** [comment]
Hi @mmclane - thanks for the feedback.
I do have a question, are you using the [native github integration](https://docs.env0.com/docs/github-templates) or are using a [personal access tokens](https://docs.env0.com/docs/access-tokens)?
