### ISSUE TITLE
Deleting a resource manually corrupts the provider

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terraform-provider-env0#155]
1. Create the following resource and apply it:
```
resource "env0_template_project_assignment" "assignment" {
  template_id = "my_template_id"
  project_id = "my_project_id"
}
```
2. Manually using env0 UI, remove the template or simply un-assign it from the project
3. Run `terraform plan` again
4. Plan fails, `could not find projectId in template`

Reason:
On every Read, we fail if the resource already exists. However, we should only fail those if this is a new resource `d.IsNewResource`.
Otherwise, we need to `d.SetId('')`.

This bug applies to all resources

See [these lines from aws TF provider](https://github.com/hashicorp/terraform-provider-aws/blob/e86fca35f8f14709be928028a5550f29bbb21bc6/internal/service/s3/bucket.go#L830-L834) for an example.

**Comment by eranelbaz** [comment]
Resolved by #202
