### ISSUE TITLE
Project Policy - Requires Approval Default behavior is inconsistent with manual project creation

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#201]
When creating a project manually, the project policy setting "Approve plans automatically for new environments" is un-checked by default. 

When creating a project with terraform provide the project policy setting "Approve plans automatically for new environments" is checked by default.

This is also confusing because the UI and Terraform Provider field are opposite statements:
 "Approve Plans Automatically for New Environments" unchecked/false === "requires_approval_default"  true

**Comment by RLRabinowitz** [comment]
Hey @away168 I have a few questions

> When creating a project with terraform provide the project policy setting "Approve plans automatically for new environments" is checked by default.

Looking at the code I see that in the terraform provider let's backend decide the default policy, both if no `env0_project_policy` resource exists, and if `env0_project_policy` exists but `requires_approval_default` is not defined.
Can you please add steps to reproduce?

> This is also confusing because the UI and Terraform Provider field are opposite statements:
"Approve Plans Automatically for New Environments" unchecked/false === "requires_approval_default" true

We can change `requires_approval_default` to something like `automatic_approval_default`, but that's gonna be a breaking change. Is it worth a breaking change?

**Comment by away168** [comment]
sample code:

```

terraform {
  required_providers {
    env0 = {
      source  = "env0/env0"
    }
  }
}

provider "env0" {
}

resource "env0_project" "project" {
  name = "tf provider test"
}

resource "env0_project_policy" "policy" {
  project_id = env0_project.project.id
  include_cost_estimation = true
}
```
creates this:
![env0 - Project Settings-2022-01-31 at 14 10 51](https://user-images.githubusercontent.com/2107354/151881517-57f0ed4f-a0c5-49bc-9aa8-7bcf71148622.png)

but i'm expecting this:
![env0 - Project Settings-2022-01-31 at 14 11 19](https://user-images.githubusercontent.com/2107354/151881581-b48f4231-6089-4537-b2f1-1c60e00a34b2.png)

I'm in favor of changing the TF provider or backend field value as a breaking change and make sure we change the Minor version of the TF provider to help signify this breaking change.

**Comment by samuel-br** [comment]
@away168 @RLRabinowitz  Hey, do we have bottom line about fix it through the provider? the main issue @away168  talked about can be fix very easily from the provider, we just need to add default value of false to  `requires_approval_default `, LMK what you think and if it can close this issue

**Comment by RLRabinowitz** [comment]
@samuel-br Yes, sounds like that would do the trick
