### ISSUE TITLE
Handle drift - general

### ISSUE THREAD

**Issue by eranelbaz** [env0/terraform-provider-env0#205]
as we did in https://github.com/env0/terraform-provider-env0/pull/202

we need to do that for ALL of our resources.

Generally:
- add a condition check for determine if (isNotANewResource && NotFound/Deleted) then
- call `setId("")` to invoke destroy
- now state is synced.

**Comment by yaronya** [comment]
@eranelbaz I'm closing this one as it's too generic and we already handled through it several reousrces. We need to open an issue per resource type such as #278
