### ISSUE TITLE
Add README that explains how to create a new resource/data

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terraform-provider-env0#206]
There are a lot of common things that have to be addressed when creating a resource/data.
When taking a look at the most known terraform providers, you see that those issues are usually not solved by DRYing out code. They're solved by making sure the logic is addressed in each resource/data

We should add some readme/guidebook that lists what has to be addressed in each resource/data. For example:

Resource:

- When to `d.setOk`, and when not to. What's the expected behaviour for drift detection on multiple scenarios
- Doing `d.setId('')` for existing resources that were deleted, on read (for drift detection on deleted resources)
- What to test

**Comment by yaronya** [comment]
@TomerHeber I'd like to assign this to you so we can note some cool stuff you've done recently within:
1. Handling drifts
2. Read/Write resource schema
3. `safeSet` 
and etc.

Feel free to add w/e you felt during the previous weeks regarding your recent implementations 🙏 
I believe this would yield a significant value for newcomers 💪

**Comment by TomerHeber** [comment]
> @TomerHeber I'd like to assign this to you so we can note some cool stuff you've done recently within:
> 
> 1. Handling drifts
> 2. Read/Write resource schema
> 3. `safeSet`
>    and etc.
> 
> Feel free to add w/e you felt during the previous weeks regarding your recent implementations 🙏 I believe this would yield a significant value for newcomers 💪

@yaronya - will do!
