### ISSUE TITLE
Should not allow for readonly+required+no value

### ISSUE THREAD

**Issue by eranelbaz** [env0/terraform-provider-env0#217]
The bug is -
1. In TF Provider, create a variable with no value, `is_read_only = true`, `is_required = true`.
2. Apply - Successful (Shouldn't be)
3. Go to the variables page in env0, see your variable there. Try to add a new one and save
4. Failed, validation failed since var can't be readonly+required, and have no value

What needs to be done here is to add validation that throws exception when both are set to `true`

**Comment by samuel-br** [comment]
> What needs to be done here is to add validation that throws exception when both are set to `true`

Only when value is empty or generally? 

>Failed, validation failed since var can't be readonly+required, and have no value

also do we need permit creation of variable with no value ?
