### ISSUE TITLE
support cloud cost credentials 

### ISSUE THREAD

**Issue by eranelbaz** [env0/terraform-provider-env0#218]
We'd like to add support for our cost credentials.
We'd need the following new resources (and data for each resource)

### cost_credentials_project_assignment

Exactly the same as `cloud_credentials_project_assignment` resource and data. The only difference is that we use different APIs:
* [Create](https://developer.env0.com/docs/api/b3A6MTkyNjc1NzI-associate-cost-credentials-with-project)
* [Delete](https://developer.env0.com/docs/api/b3A6MTkyNjc1NzU-dissociate-cost-credentials-from-project)
* [Read](https://developer.env0.com/docs/api/b3A6MTkyNjc1NzM-list-cost-credentials-associated-to-project) - Notice the response format is different than [this](https://developer.env0.com/docs/api/b3A6MTkyNjc1NzE-list-deployment-a-project-s-deployment-credentials)

### aws_cost_credentials

Exactly the same as `aws_credentials` resource and data (which is a deploy credential, not a cost credential). The schema is exactly the same, and the API calls are the same. The only difference is that the `type` that should be `AWS_ASSUMED_ROLE`:
* [Create](https://developer.env0.com/docs/api/b3A6ODc4NjAwOQ-create-cloud-provider-cost-credentials) should be called with correct `type` and data in `value`
* data should filter by type = `AWS_ASSUMED_ROLE`

### azure_cost_credentials

Similar to `aws_cost_credentials` resource and data. Should use the same APIs, where type is `AZURE_CREDENTIALS `. For the schema - see [docs](https://developer.env0.com/docs/api/b3A6ODc4NjAwOQ-create-cloud-provider-cost-credentials) - value:
* clientId - required
* clientSecret - required and sensitive
* tenantId - required
* subscriptionId - required
Other than the schema, differences in API calls are as follows:
* [Create](https://developer.env0.com/docs/api/b3A6ODc4NjAwOQ-create-cloud-provider-cost-credentials) should be called with correct `type` and data in `value`
* data should filter by type = `AZURE_CREDENTIALS `

### google_cost_credentials

Similar to `aws_cost_credentials` resource and data. Should use the same APIs, where type is `GCP_CREDENTIALS`. For the schema - see [docs](https://developer.env0.com/docs/api/b3A6ODc4NjAwOQ-create-cloud-provider-cost-credentials) - value:
* tableId - required
* secret - required and sensitive
Other than the schema, differences in API calls are as follows:
* [Create](https://developer.env0.com/docs/api/b3A6ODc4NjAwOQ-create-cloud-provider-cost-credentials) should be called with correct `type` and data in `value`
* data should filter by type = `GCP_CREDENTIALS`

**Comment by RLRabinowitz** [comment]
When implementing, feel free to create common API logic, and read/create/delete logic, where necessary

**Comment by samuel-br** [comment]
@RLRabinowitz  does the update of `aws_credentials `with `access_key `and `secret_access_key `relevant to `aws_cost_cred `to?

**Comment by RLRabinowitz** [comment]
@samuel-br Answered [here](https://env0.slack.com/archives/C01QBBEGBEH/p1647435402835139)

**Comment by yaronya** [comment]
@eranelbaz @samuel-br please note that we should also support assigning a cost credential to a project (which means that we need to have additional "assignment" resources like we do with all other resource types)
