### ISSUE TITLE
Automatic generate doc on release

### ISSUE THREAD

**Issue by eranelbaz** [env0/terraform-provider-env0#220]
#### Motivation / Problem / The Why❔:
Make our lives easier :ocean: 

Currently, our release process includes opening PR to update the docs

#### Expected Result / DoD ✅:
that should be an automated process by either -
- CI check that we updated our docs as part of the PR
- run docs generation on release

**Comment by yaronya** [comment]
Docs are now auto-generated on every push to master. The release README notes how to validate that the docs has been generated. Closing this one.
