### ISSUE TITLE
Add support for AWS access key Credentials

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terraform-provider-env0#232]
Terraform Provider should support upcoming cloud deployment credentials

### `aws_credentials` resource:

Should also support AWS access keys:
- Add new fields to `aws_credentials` - `access_key_id` and `secret_access_key`
- [`arn`, `external_id`] and `[`access_key_id`, `secret_access_key`] should be mutually exclusive!
  - If `arn` is set, then `external_id` is optional, but `access_key_id` and `secret_access_key` cannot be set
  - If `access_key_id` is set then `secret_access_key` is mandatory, and both `arn` and `external_id` cannot be set
- For the create API call
  - If `arn` is set, `type` should be `AWS_ASSUMED_ROLE_FOR_DEPLOYMENT`. If `access_key_id` is set, `type` should be `AWS_ACCESS_KEYS_FOR_DEPLOYMENT`
  - Build the value object according to the type. Either `{ roleArn, externalId }` or `{ accessKeyId, secretAccessKey }`
- When importing, only accept credentials that are AWS (`AWS_ASSUMED_ROLE_FOR_DEPLOYMENT` or `AWS_ACCESS_KEYS_FOR_DEPLOYMENT`). This is can be done in a separate issue though

**Comment by yaronya** [comment]
@GiliFaroEnv0 @RLRabinowitz was this fully implemented? if so, can we please close this issue?
