### ISSUE TITLE
Terragrunt Working Directory support

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#233]
Please add TF working directory to env0 environment resource.

**Comment by TomerHeber** [comment]
Template resource accept two types: `terraform` and `terragrunt`. 
When selecting `terragrunt`, the API also accepts a `path` body param, but that's missing from the Terraform provider.

See API request body:
```
{
  "retry": {
    "onDeploy": null,
    "onDestroy": null
  },
  "sshKeys": [],
  "terraformVersion": "0.15.1",
  "type": "terragrunt",
  "description": "test!!!",
  "name": "terragrunt",
  "repository": "https://github.com/TomerHeber/detect-file-type",
  "isGitHubEnterprise": false,
  "isGitLabEnterprise": false,
  "isBitbucketServer": false,
  "bitbucketClientKey": null,
  "gitlabProjectId": null,
  "isGitLab": false,
  "tokenName": "",
  "tokenId": "",
  "githubInstallationId": 23935897,
  "revision": "master",
  "path": "test/folder",
  "projectIds": [
    "a8cd257c-3097-4714-82e2-b51c049b0bea"
  ],
  "organizationId": "42f8d807-42c8-435c-be2d-97774758161f"
}
```

**Comment by TomerHeber** [comment]
@away168 -
Reviewing the code, it seems that the "path" body param is already in the code. Requesting clarifications.

**Comment by TomerHeber** [comment]
Andrew confirmed that this issue could be closed. (Functionality already exists).

**Comment by TomerHeber** [comment]
@away168,

Thank you for the clarification. I will handle it.
