### ISSUE TITLE
env0 Template does not validate Terraform Version field

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#240]
> Error: could not create template: 400 Bad Request: Invalid terraform version v0.14.0
> with module.env0_template.template["us-east"],
> on modules/environment/main.tf line 30, in resource "env0_template" "template":
> 30: resource "env0_template" "template" {

**Comment by ImIOImI** [comment]
You can reproduce this via
```
resource "env0_template" "template" {
  name                   = "name"
  repository             = local.repo
  path                   = "fake/path"
  terraform_version      = "v0.14.0"
  revision               = local.revision
  github_installation_id = local.github-id
  type                   = "terraform"
}
```

This will pass during a PR and fail during a deploy

**Comment by yaronya** [comment]
In env0 UI we prefetch all current available TF versions and display them. I believe this might be ROI negative for the TF provider so I think that adding a regex validation should be enough (to avoid those confusing `v` prefixes). WDYT @away168?
