### ISSUE TITLE
Handle drift in environment and project resources

### ISSUE THREAD

**Issue by samuel-br** [env0/terraform-provider-env0#250]
Drift not detected, when removing  a resource through Env0 site for example, Provider will throw error instead of removing the resource from state.
**this issue is relevant for project resource and environment resource only**
**other resources are taking care in #205 and #225**

**Comment by yaronya** [comment]
We've decided there's no need to handle drifts in these resources as they aren't really deleted (but only "archived"). Also, it'd be preferable to wait for some customer input before proceeding on this one.
