### ISSUE TITLE
Add unit tests for pr#25 (organizationId in Projects)

### ISSUE THREAD

**Issue by roni-frantchi** [env0/terraform-provider-env0#26]
Merged #25 to resolve #13 - but no ut since we haven't merged in the testbed.  
We should add a proper unit test once the testbed's in place

**Comment by roni-frantchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TF Provider - Can't create project](https://trello.com/c/it7aD4Rz/3281-tf-provider-cant-create-project)

**Comment by avnerenv0** [comment]
@roni-frantchi @yaronya this is resolved in project_test.go , right?

**Comment by yaronya** [comment]
@avnerenv0 indeed
