### ISSUE TITLE
go staticcheck checks are failing.

### ISSUE THREAD

**Issue by TomerHeber** [env0/terraform-provider-env0#262]
I have noticed that go staticcheck is finding issues in the code (mostly minor).
Recommendation:

1. Modify code so go staticcheck passes (Fix all issues).
2. Enforce go staticcheck via pipeline and pre-commit hooks. 

E.g.: `should omit comparison to bool constant, can be simplified to !isValid (S1002)`

**Comment by yaronya** [comment]
Great suggestion @TomerHeber 
Feel free to incorporate any golang best practices that our repo is missing 🙏
