### ISSUE TITLE
Feature Request: Add a Provider for Private Modules

### ISSUE THREAD

**Issue by kderck** [env0/terraform-provider-env0#264]
Hi Env0. 

Please could you consider adding a `Resource` for creating, and destroying `Private Modules`. While I understand they are likely only created once. I'd just like to be able to automate this.

**Comment by omry-hay** [comment]
> Hi Env0.
> 
> Please could you consider adding a `Resource` for creating, and destroying `Private Modules`. While I understand they are likely only created once. I'd just like to be able to automate this.

Hi @kderck 

Thanks for submitting this issue,  and this is defiantly on our immediate roadmap and one of the next enhancement we are going to add to our Terraform provider. 

However, we already have an [open issue](https://github.com/env0/terraform-provider-env0/issues/198) to support that, so I am going to close this one.
Feel free to follow the original issue and get updates when it will be released.

Thanks
