### ISSUE TITLE
Add support for assigning a notification to a project

### ISSUE THREAD

**Issue by yaronya** [env0/terraform-provider-env0#280]
We've recently implemented the `env0_notification` resource but yet it's impossible to actually use it as the provider doesn't expose any means of assigning such notification to a project.

We need to create such assignment resource (same as we do with a lot of other resources in the provider).
Note that in this case, the assignment also holds a list of preferred event types to get notified upon (See it on env0 UI via `Project Settings -> Notifications`)

**Comment by TomerHeber** [comment]
@yaronya - observing the notifications in the UX:
When I create a notification it's added to all projects. Is it possible that at the moment it's a global setting?
