### ISSUE TITLE
Add data source for user

### ISSUE THREAD

**Issue by eranelbaz** [env0/terraform-provider-env0#298]
Add `data env0_user`
the query will be by email - and return user details from https://developer.env0.com/docs/api/b3A6MTkyNjc1OTE-list-users

need to expose only user id (can be by `id`)

**Comment by yaronya** [comment]
@away168 would like your input on this one.
Did we have users requesting an `env0_user` resource? (i.e creating/inviting users via TF) 
Asking because this issue only tackles the data resource
