### ISSUE TITLE
Environment resource `configuration` field is affected by global scope variables

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terraform-provider-env0#318]
Consider the following TF:
```
resource "env0_environment" "env" {
  name = "name"
  project_id = "my-project-id"
  template_id = "my-template-id"
  force_destroy = true
  configuration {
    name = "myvar"
    value = "value"
  }
}

resource "env0_configuration_variable" "global_variable" {
  name  = "anothervar"
  value = "anothervalue"
}
```

On first apply, this works as intended.
On a second apply, the `env0_environment`'s plan get's messed up, and affected by the global variable (variable defined at organization level). The plan would be something like this:

```
  # env0_environment.envy has been changed
  ~ resource "env0_environment" "envy" {
        id                               = "ID"
        name                         = "name"
        # (10 unchanged attributes hidden)

      ~ configuration {
          ~ name         = "myvar" -> "anothervar"
          ~ value         = "new" -> "anothervalue"
            # (4 unchanged attributes hidden)
        }
      + configuration {
          + name         = "myvar"
          + type           = "environment"
          + value          = "value"
        }
    }
```

The reason is that the `/configuration` API is getting both `organizationId` and `environmentId` in the query parameters, so it returns a merged cofiguration of both organization-level variables and environment-level variables

We should not send `organizationId` to that API when considering variables in `configuration` field in `env0_environment`

**Note:** the behaviour is the same for `data env0_configuration_variable` and should be changed there as well. There, we only allow for a single specific scope (`project_id`/`template_id`/...), and we merge the configuration with organization variables. Let's remove this configuration merge (as-in, let's stop putting `organizationId` in the request when scope is not `ScopeGlobal`)

**Comment by RLRabinowitz** [comment]
The above info is partially correct. We SHOULD not include organizationId in the request.
However, seems like this bug is actually a REGRESSION, probably introduced in https://github.com/env0/terraform-provider-env0/pull/314

The configuration blocks of `environment_resource` were wrongfully stored, taking global variables into consideration as well. However, this was never an issue, because Read queried configuration variables in the same way, also taking global variables into consideration. So, the state was wrong, but on apply not changes were detected if there actually no changes.

We should dig deeper and see what has changed this

**Comment by RLRabinowitz** [comment]
Steps to recreate might be wrong.
The environment might need to be created in 0.2.31, and then redeployed in  0.2.32 again. Then every subsequent apply would still produce this issue

**Comment by TomerHeber** [comment]
> The above info is partially correct. We SHOULD not include organizationId in the request. However, seems like this bug is actually a REGRESSION, probably introduced in #314
> 
> The configuration blocks of `environment_resource` were wrongfully stored, taking global variables into consideration as well. However, this was never an issue, because Read queried configuration variables in the same way, also taking global variables into consideration. So, the state was wrong, but on apply not changes were detected if there actually no changes.
> 
> We should dig deeper and see what has changed this

https://github.com/env0/terraform-provider-env0/pull/314/files#diff-5dfeada10c7bdbcd4234860009b1a414cb4d99b87791eb4cb6ad6c3b7c3f703aR212
