### ISSUE TITLE
Add data source for teams

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#340]
Add a new data source to list all teams in the org.
This should provide a list of all the teams names in a given Org.

This list should be able to be used to create a team data source based on the names returned.

Usage example:

data "env0_teams" "all_teams" {
    organization = "1234"                       # The organization is normally part of the API key, just placed this here as an example
    search          = "Some search text "  # This is not part of the current ticket requirement, but an example of how this can be used in the future....
}

data "env0_team" "teams" {
    for_each = tomap(data.env0_teams.all_teams.names)
    name      = each.value
}

Relevant API:
  - https://developer.env0.com/docs/api/b3A6MTkyNjc2MDg-list-teams

**Comment by yaronya** [comment]
Hello @chris-ackerman-dentsu 
Thanks for the suggestion! We'll put this into our ongoing issues 💪
