### ISSUE TITLE
Add data source for templates

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#341]
Add a new data source to list all templates in the org.
This should provide a list of all the templates names in a given Org.

This list should be able to be used to create a template data source based on the names returned.

Usage example:

data "env0_templates" "all_templates" {
organization = "1234" # The organization is normally part of the API key, just placed this here as an example
search = "Some search text " # This is not part of the current ticket requirement, but an example of how this can be used in the future....
}

data "env0_template" "templates" {
for_each = tomap(data.env0_templates.all_templates.names)
name = each.value
}

Relevant API:
  - https://developer.env0.com/docs/api/b3A6NTg5Mjk3MQ-list-templates

**Comment by yaronya** [comment]
Hello @chris-ackerman-dentsu 
Thanks for the suggestion! We'll put this into our ongoing issues 💪
