### ISSUE TITLE
data env0_template missing bitbucket_client_key

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#352]
Cannot retrieve `bitbucket_client_key` from data `env0_template`

There seems to be other parameters also missing from the data object.

e.g. description

**Comment by TomerHeber** [comment]
Hi @away168 ,

In general, it's preferred to add fields to the data object when needed (and not just expose everything).
Other than `bitbucket_client_key`, have you received requests to expose other fields?

**Comment by away168** [comment]
@TomerHeber 
Please expose the following fields:

bitbucket_client_key (String) the bitbucket client key used for integration
description (String) description for the template
is_bitbucket_server (Boolean) true if this template uses bitbucket server repository
is_github_enterprise (Boolean) true if this template uses github enterprise repository
ssh_keys (List of Map of String) an array of references to 'data_ssh_key' to use when accessing git over ssh
