### ISSUE TITLE
Add new option to template which populates variables from source code

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#359]
Add a new option to the env0_template resource to populate credentials from source code
Best suggestion would be to use a true false variable with false being the default

Usage example:

resource "env0_template" "example" {
  name        = "example"
  description = "Example template"
  repository  = "https://github.com/env0/templates"
  path        = "aws/hello-world"
  ssh_keys    = [data.env0_ssh_key.my_key]
  populate_vars_from_source_code = true
}

Relevant API:
    https://developer.env0.com/docs/api/b3A6MjcwNzkzNTQ-generate-terraform-variables-from-repository

**Comment by TomerHeber** [comment]
Hi @chris-ackerman-dentsu -
How about a data source to extract these values? (instead of `populate_vars_from_source_code`).

**Comment by TomerHeber** [comment]
Hi @chris-ackerman-dentsu - reaching out again for your feedback.

Thanks!

**Comment by chris-ackerman-dentsu** [comment]
Hi @TomerHeber.
I actually think that is a great idea. Then we can assign the variables as we want them and probably in different formats too, depending on how the values are returned (string vs map as an example).
Just one question, I know you guys are removing env0_configuration_variable assignment to environments, but that will not impact assignment to a template right? If it does then it might become a problem doing it as a data source instead of a function.

**Comment by yaronya** [comment]
> I know you guys are removing env0_configuration_variable assignment to environments

This isn't final TBH, we might revert it in a future version. We are taking it internally currently to figure whether we really wanna go that path.

> that will not impact assignment to a template right

That is correct :)

---

If that works for you, please consider closing this issue. Beyond that, feel free to reach out and ask any other question.

**Comment by chris-ackerman-dentsu** [comment]
Hi @yaronya  Should the issue not be closed once the code is implemented?

**Comment by TomerHeber** [comment]
@chris-ackerman-dentsu - please keep open. Thanks!
