### ISSUE TITLE
Environment resource does not support new templateless creation

### ISSUE THREAD

**Issue by athak** [env0/terraform-provider-env0#374]
Hi,
As of a few weeks ago, [environments can be created without a template](https://docs.env0.com/changelog/environment-without-template), which is very useful. 

However, the `env0_environment` resource, still requires a template id to be supplied, effectively not allowing this kind of environment to be created via Terraform.

It would be great to add support of templateless environment to the resource.

Thanks,
Atha

**Comment by TomerHeber** [comment]
@omry-hay @yaronya - I'm marking it as blocked for now. I recommend discussing this internally to decide what would be the best way to add support for this feature in the provider.

**Comment by yaronya** [comment]
@TomerHeber I agree, we'll take this internally and report back

**Comment by TomerHeber** [comment]
Suggested solution:

When creating an env, to extend the current existing variables for creation to include the VCS and other relevant data that is needed, all under a new fields template_data. if such a field exists, we use the api client to create a template by the given data, and pass isSingleUse=true. the returned template id is then used as in the regular creating of env, and we also pass isSingleUse=true

**Comment by yaronya** [comment]
@TomerHeber what's the status of this one?

**Comment by TomerHeber** [comment]
@yaronya - the schema is available. I still need to implement the "resource" code where there are two cases (one with a template in the schema the other with not).
I've been carefully and slowly working towards it for several reasons:
1. keep reviews small.
2. avoid breaking existing code.
3. avoid duplicating code (a lot of the work has been around refactoring and using the read/write serializers).
