### ISSUE TITLE
Refactor resources/data to use the new serialization/deserialization logic

### ISSUE THREAD

**Issue by yaronya** [env0/terraform-provider-env0#376]
We've recently introduced a new way of serialize/deserialize structs to/from API types and TF schema structure. 
This has been done to all resources moving forward from that point, but we still have plenty of resources and data resources that aren't using this utility. We should make an effort to align our codebase to use this utility.

Please make sure to split it to several pull requests as it might be a big effort.
Also - luckily all our resources are covered with UTs so if something would break - we'd know that on development phase 💪

**Comment by yaronya** [comment]
@TomerHeber I see we've made a lot of progress with this effort. Can you share what's left? or how close are we to completing this?

**Comment by TomerHeber** [comment]
@yaronya - I think it's almost done in all the places that make sense.
If there is something left, it's rather small.
I'll compose a list (if I find any left).

**Comment by TomerHeber** [comment]
@yaronya - environment is a big one still left.
There are some challenges to it in general. I'm slowly refactoring.
