### ISSUE TITLE
Support resolving terraform version from code for template resource

### ISSUE THREAD

**Issue by ImIOImI** [env0/terraform-provider-env0#384]
## Bug Description
After [this commit](https://github.com/env0/terraform-provider-env0/commit/633ce830908a61ed0227b6229a6dbca9009be98b) the functionality of the way Env0 sets the terraform_version was broken. Previously when the terraform version wasn't set, Env0 would grab the version to run the code from the required_version in the code template. The following were valid cases:

```terraform
resource "env0_template" "template" {
  ...
  terraform_version = ""
  ...
}

resource "env0_template" "template" {
  ...
  terraform_version = null
  ...
}

resource "env0_template" "template" {
  ...
  #no version set
  ...
}
```

Now, the default behavior is to set the terraform version to 0.15.1. This broke all env0 environments that relied on the required_version in the code template.

## Justification
Using the required_version in the code template makes it impossible for an engineer to accidently upgrade the Terraform version by running it locally.

By allowing required_version in a monorepo we can upgrade environments in a stepwise manner. 

## Acceptance Criteria
* As a user, I expect when terraform_version is passed `null` or `""` to have Env0 rely on the required_version in the code template
* As a user, I expect when terraform_version is not set to have Env0 rely on the required_version in the code template
* As a user, I expect that when there's a conflict between the template code's required version and a set version in the env0_template for Env0's value to take prescedence.

**Comment by TomerHeber** [comment]
@ImIOImI 
Could you please clarify the last bullet point? What should take precedence over what?

**Comment by ImIOImI** [comment]
> @ImIOImI Could you please clarify the last bullet point? What should take precedence over what?

@TomerHeber This is the way it worked before the above-mentioned commit and the way it works now. The intentionality is to make sure that current functionality isn't disrupted.

Hypothetically, let's imagine that we have an env0_template like the following:
```terraform
resource "env0_template" "template" {
  ...
  terraform_version = "0.13.0"
  path                      = "/path/to/example"
  ...
}
```

if the code template (`/path/to/example`) defines the required_version as "0.12.0" then the version defined in the env0_template should take precedence.

**Comment by TomerHeber** [comment]
@ImIOImI - thanks for clarifying.

**Comment by yaronya** [comment]
Hi @ImIOImI 
As you can see from the attached [commit](https://github.com/env0/terraform-provider-env0/commit/633ce830908a61ed0227b6229a6dbca9009be98b), the default value for the `terraform_version` attribute of `env0_template` resource has always been `0.15.1`.  (See [this line](https://github.com/env0/terraform-provider-env0/commit/633ce830908a61ed0227b6229a6dbca9009be98b#diff-cd208832e068e737327ee5222f926523e6464d681cb34df6a74973673cfcf49cL156) specifically)
We do not take into consideration the `terraform.required_version` attribute. In fact, I don't think the provider framework even share this information in their available context.

This is the same behavior as we have in our UI (i.e same default version is used in both when a user doesn't specify a specific version)

**Comment by scott-the-programmer** [comment]
It's worth noting that the commit https://github.com/env0/terraform-provider-env0/commit/633ce830908a61ed0227b6229a6dbca9009be98b is relatively recent (31st March) - so it's likely that this discrepancy is more to do with regression

**Comment by TomerHeber** [comment]
@yaronya I'm not saying if it's a good idea or not.
But it's possible to store the version in the provider meta and default to it (E.g. add it to the ApiClient).

Regardless, IMHO: `null` and `""` shouldn't be valid values.

```
func configureProvider(version string, p *schema.Provider) schema.ConfigureContextFunc {
	userAgent := p.UserAgent("terraform-provider-env0", version)

	return func(ctx context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
		httpClient, err := http.NewHttpClient(http.HttpClientConfig{
			ApiKey:      d.Get("api_key").(string),
			ApiSecret:   d.Get("api_secret").(string),
			ApiEndpoint: d.Get("api_endpoint").(string),
			UserAgent:   userAgent,
			RestClient:  resty.New(),
		})
		if err != nil {
			return nil, diag.Diagnostics{diag.Diagnostic{Severity: diag.Error, Summary: err.Error()}}
		}

		return client.NewApiClient(httpClient), nil
	}
}
```

**Comment by yaronya** [comment]
> It's worth noting that the commit https://github.com/env0/terraform-provider-env0/commit/633ce830908a61ed0227b6229a6dbca9009be98b is relatively recent (31st March) - so it's likely that this discrepancy is more to do with regression

@scott-the-programmer the behavior of having the `terraform_version` to default to `0.15.1` isn't new. Looking at the git history, it seems like it has always been like that.

However, @scott-the-programmer @ImIOImI I think I understand your issue here. 
The env0 platform supports a value called "Resolve from terraform code", as @ImIOImI mentioned, that makes sure that the deployment would decide what version to use on runtime based on `terraform.required_version`. It's a backend feature, so it got nothing to do with the provider actually. When we introduced the regex of the version, it simply blocked the provider from using this feature.

By the way, the value sent to API is `RESOLVE_FROM_TERRAFORM_CODE`. Maybe that's the value you were using previously in the provider?

Anyhow, to settle this down and provide a decent solution, we'll need to:
1. Change the value's regex to also support that value. I'd suggest to use the string `RESOLVE`. (`null` and `""` would still be using the default value)
2. Make sure docs indicate that this is a valid value and what is does.

This way we don't break the provider and we align it with the UI behavior.
@ImIOImI how that sounds?
