### ISSUE TITLE
env0_environment resource support for PR plan / apply and Alias options

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#386]
Please add support for Plan and Apply from PR & the alias option for `env_environment` resource

**Comment by mmclane** [comment]
LOL.. I was just coming in here to say the same thing!

**Comment by TomerHeber** [comment]
@away168 - could you please point me to the relevant fields in the API:
https://developer.env0.com/docs/api/2a25c8a8e3217-create-environment

Thanks!

**Comment by away168** [comment]
https://developer.env0.com/docs/api/0dd1ba20d9b2f-update-environment not sure if it's available in create environment. But update environment has it as VCS alias, `vcsCommandsAlias`. Not sure what else is required (if anything)

**Comment by TomerHeber** [comment]
@away168 
Just the third checkbox there? anything else?

![image](https://user-images.githubusercontent.com/12767692/169699037-380635ba-8b6d-4b0e-8dd1-550959166b99.png)
