### ISSUE TITLE
Environment resource does not have a way to set an environment alias (Atlantis-style workflow)

### ISSUE THREAD

**Issue by arunnair-7** [env0/terraform-provider-env0#396]
env0 not supports https://docs.env0.com/docs/plan-and-apply-from-pr-comments 
But the option to set an environment alias does not seem be be available on the TF `env0_environment` resource. 
Using TF provider version 1.0.5

https://registry.terraform.io/providers/env0/env0/latest/docs/resources/environment

**Comment by TomerHeber** [comment]
@arunnair-7 

This should be available in the next release.
See: https://github.com/env0/terraform-provider-env0/issues/386
