### ISSUE TITLE
Add data source for getting a list of Notification Targets

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#397]
Add a new data source to list all Notification Targets in the org.
This should provide a string list of all the notification targets in a given Org.

This list should be able to be used to create a notification data source based on the names returned.

Usage example:

data "env0_notifications" "notification_targets"{}

data "env0_notification" "my_notifications {
for_each = toset(data.env0_notifications.notification_targets.names)
name = each.value
}

Relevant API:
https://developer.env0.com/docs/api/f22e17faa92dd-list-notification-endpoints

**Comment by TomerHeber** [comment]
@yaronya - should I implement this?
