### ISSUE TITLE
Integration tests rely on actual configuration variable

### ISSUE THREAD

**Issue by avnerenv0** [env0/terraform-provider-env0#4]
`examples/003_configuration_variable/main.tf` relies on the organization having 
- A configuration variable called `AWS_DEFAULT_REGION` in the organization scope.
- A configuration variable called `AWS_DEFAULT_REGION` in the project scope, in the `Default Organization Project` project.

This should _at least_ be documented but preferably fixed so the integration tests can run on a "clean" organization and not depend on prior manual setup, besides the API Key.

**Comment by liranfarage89** [comment]
- The code in `002_project/main.tf` assumes that there is a default project with the name Default Organization Project. If there is no such project, the test fails.

```
│ Error: Could not find a project with name: Default Organization Project
│ 
│   with data.env0_project.default,
│   on main.tf line 1, in data "env0_project" "default":
│    1: data "env0_project" "default" {
│ 
╵

```
