### ISSUE TITLE
env0_template import issue github_installation_id

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#401]
Hi. So I am trying to import templates from git and I want to use the GitHub App that env0 installed into my ORG to import the templates.
It works when you use the SSH KEY but then you do not get GitHub integration like plan on every push or PR plans.

We find GitHub repositories that are templates by GitHub topic in our ORG like this:

```
data "github_repositories" "template_list" {
  query = "org:${var.github_org} topic:${var.github_topic}"
}

data "github_repository" "repo" {
  for_each  = toset(data.github_repositories.template_list.full_names)
  full_name = each.value
}
```

This code works fine, but integrations do not work:
```
resource "env0_template" "template" {
  for_each    = toset(data.github_repositories.template_list.full_names)
  name        = data.github_repository.repo[each.key].name
  description = data.github_repository.repo[each.key].description
  repository  = data.github_repository.repo[each.key].ssh_clone_url
  ssh_keys    = [data.env0_ssh_key.ssh_key]
}
```

This is the code we want to use but it does not work:
```
resource "env0_template" "template" {
  for_each               = toset(data.github_repositories.template_list.full_names)
  name                   = data.github_repository.repo[each.key].name
  description            = data.github_repository.repo[each.key].description
  repository             = data.github_repository.repo[each.key].full_name
  terraform_version      = "1.1.9"
  github_installation_id = xxxxxxxx
}
```

The plan output is what led me to the idea that the github_installation_id is not being set:
```
  env0_template.template["gdo-xxxx-xxxxxxxxx/team-test"] will be updated in-place
  ~ resource "env0_template" "template" {
        id                     = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        name                   = "team-test"
      ~ repository             = "org-xxxxxxxxxxx@github.com:gdo-xxxx-xxxxxxxxx/team-test.git" -> "gdo-xxxx-xxxxxxxxx/team-test"
      ~ ssh_keys               = [
          - {
              - "id"   = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              - "name" = "GH"
            },
        ]
      ~ terraform_version      = "0.15.1" -> "1.1.9"
         (8 unchanged attributes hidden)
    }
```

It is trying to remove the SSH keys which is correct, but not setting the GitHub App installation ID into the state file.
Errors on existing repo:
```
│ Error: could not update template: 400 Bad Request: You have no access to that repository.
│ 
│   with env0_template.template["gdo-xxxx-xxxxxxxxx/team-test"],
│   on main.tf line 16, in resource "env0_template" "template":
│   16: resource "env0_template" "template" {
│ 
╵
```

On a new repo it seems to set the GitHub App ID but I still get the same error:
```
   env0_template.template["gdo-xxxx-xxxxxxxxx/factory-modules"] will be created
  + resource "env0_template" "template" {
      + github_installation_id = 2xxxxxx4
      + id                     = (known after apply)
      + is_bitbucket_server    = false
      + is_github_enterprise   = false
      + is_gitlab_enterprise   = false
      + name                   = "factory-modules"
      + repository             = "gdo-xxxx-xxxxxxxxx/factory-modules"
      + terraform_version      = "1.1.9"
      + type                   = "terraform"
    }
```

Errors on new repo:
```
╷
│ Error: could not create template: 400 Bad Request: You have no access to that repository.
│ 
│   with env0_template.template["gdo-xxxx-xxxxxxxxx/factory-modules"],
│   on main.tf line 16, in resource "env0_template" "template":
│   16: resource "env0_template" "template" {
│ 
```

I did confirm that the APP ID is the correct one, I hope:
![Screenshot_20220530_131348](https://user-images.githubusercontent.com/87015771/170981205-68059570-c9c9-4a83-8377-e70d9d3e5487.png)
And I have tried with:
repository             = data.github_repository.repo[each.key].full_name
repository             = data.github_repository.repo[each.key].http_clone_url
repository             = data.github_repository.repo[each.key].ssh_clone_url

**Comment by yaronya** [comment]
Hi @chris-ackerman-dentsu 
Pleae consider using code markdon so it'd be easier to understand your shared code 🙏

**Comment by chris-ackerman-dentsu** [comment]
@yaronya I hope that looks better. Sorry I rarely use markdown so did not consider it...

**Comment by TomerHeber** [comment]
@chris-ackerman-dentsu 

I reviewed the code, and it seems to be correct. (I'm not sure why git_installation_id is missing).
With that said, could you try setting the repository value to a full URL:
E.g.: `https://github.com/env0/templates`

Let me know what the results are. Thanks!

**Comment by chris-ackerman-dentsu** [comment]
Great that worked! A simple thing like using the 
```
data.github_repository.repo[each.key].html_url
```
fixed it. 
There are no examples in the provider documentation for using a github installation ID. I will be sure to remember this one.
In the UI it retrieves the values for you and you have to select them from a drop down, and in the drop down it is the repo full name.
Oh and I also figured out why it was not setting the github installation ID on plan, It already set it on a previous run, so it was in the # unchanged section, that is why it was visible on a new repo, this was my bad. I guess trying to make things work and running many many plans just messes with one's brain...

Thank you

**Comment by TomerHeber** [comment]
@chris-ackerman-dentsu - thank you for confirming!
I'll add an example to the documents. (Please keep the issue open - thanks!).
