### ISSUE TITLE
Do not recreate env0 environment ID - if environment has a deployment failure

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#402]
current behavior:
when a deployment fails, env0 marks env0_environment as inactive.
on a subsequent run the env0 (provider) creates a new env0_environment. 

issue:
this makes debugging hard - as env0_environment with the deployment failure logs is marked as inactive and becomes difficult to find and trace.  (especially when we create a multi-tiered env0_environment deployment workflow)

desired behavior:
for any unique environment name - do not mark the env0_environment resource as inactive.
instead, trigger a new deployment in the existing env0_environment resource with the same name & template.

**Comment by jwjs36987** [comment]
As best as I can understand, the sequence is as follows:
1. The env0 deployment fails - this marks the terraform resource as failed
2. The next time terraform is run, the terraform core logic deletes the failed resource (the environment) causing env0 to run a destroy operation. This is particularly bad if other infrastructure is dependent on the resources in this environment
3. Terraform creates a new environment / deployment which obscures the logs from the previous failure.

Hiding the logs is not ideal. Running destroy because the terraform apply failed can cause significant issues with other environments.

**Comment by away168** [comment]
@TomerHeber just wanted to make sure we're clear. 
one of the key behaviors that we would like to address is the deployment failure causing the environment to be destroyed.  this should be stopped, a deployment failure, should just be a deployment failure. but env0 environment should be re-used on subsequent run of the TF code.  

current behavior: Terraform destroy is called.

**Comment by TomerHeber** [comment]
@away168 - understood.
Maybe https://developer.env0.com/docs/api/2a25c8a8e3217-create-environment needs to have a flag not to fail the request if the deployment fails.

I'm not convinced there's an easy/clean fix to be done in the terraform provider.

**Comment by yaronya** [comment]
@TomerHeber Sorry that I missed this thread.

We're removing the `wait_for` attribute on next version so now failed deployment on initial creation of an environment via the provider wouldn't re-create the environment anymore.

After removing it, we need to test the behavior in case environment is marked as `inactive` in env0 - would the drift be captured and the provider would require status change? @TomerHeber maybe you can already tell that.

**Comment by yaronya** [comment]
> If there's an inactive environment with the same name project_id and template_id, use it?

Not sure it's a decent path to take, since environment names in env0 aren't unique so we might "select" on the wrong environment...

**Comment by TomerHeber** [comment]
@yaronya - I think with the removal of "wait_for" this issue may go away.
I'll check about drift via inactive. But if I'm not mistaken, with the removal of "wait_for" wouldn't the environment remain in active status (because it will not be deleted by the provider)?

**Comment by yaronya** [comment]
> wouldn't the environment remain in active status (because it will not be deleted by the provider)?

IIRC, it would
The only thing I think it worth asserting is how it treats drifts, beyond that - issue indeed may go away

**Comment by TomerHeber** [comment]
@yaronya -

A few things:
1. Looks like drift is not handled properly
```func resourceEnvironmentRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	apiClient := meta.(client.ApiClientInterface)

	environment, err := apiClient.Environment(d.Id())
	if err != nil {
		return diag.Errorf("could not get environment: %v", err)
	}

	environmentConfigurationVariables, err := apiClient.ConfigurationVariablesByScope(client.ScopeEnvironment, environment.Id)
	if err != nil {
		return diag.Errorf("could not get environment configuration variables: %v", err)
	}
	setEnvironmentSchema(d, environment, environmentConfigurationVariables)

	return nil
}```
2. I'm going to assume https://developer.env0.com/docs/api/bfa512de70800-get-environment returns an environment regardless of status. The question is... is there any use-case where we want the status to cause a drift in terraform? (Let me know your thoughts).

**Comment by yaronya** [comment]
> Looks like drift is not handled properly

I'm not sure what you mean by that, but my intention was to make sure we aren't treating environment status change as drift now, as we aren't handling deployments whatsoever via the provider.

> returns an environment regardless of status

Yes.

**Comment by TomerHeber** [comment]
Deployment is no longer part of the terraform provider. This issue is no longer relevant.
