### ISSUE TITLE
Deprecate and remove `wait_for`

### ISSUE THREAD

**Issue by avnerenv0** [env0/terraform-provider-env0#424]
After some internal discussions we decided we would not like to support the `wait_for` property of the `environment` resource.

This is mainly due to 
- It's not really working well when there are failures in the environment's initial deployment - a common happening. That issue is also very hard to mitigate since TF will taint the resource. 
- We are introducing 'complex workflows' to the platform which are a much better of way of handling this use case.
- The provider should be used to configure env0, but not to "run" it, and 'wait_for' mixes the two needs.

We should deprecate this feature ASAP and remove it in the next major version.
The sooner the better - AFAIK no one is using this feature ATM.

**Comment by TomerHeber** [comment]
The deprecation message has been added. Will add a PR that removes the wait_for.
