### ISSUE TITLE
Improve harness test isolation

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terraform-provider-env0#435]
Once in a while, running the integration tests fail because some resource with the same name already exists. This error blocks all harness tests that run after it, until this resource is manually removed.

For example, if a harness test creates a `env0_team` resource with a static name "Team", and that test failed for some reason, then all subsequent tests would attempt to create a team with the same name, and will fail. We'd need to remove that team manually.
To solve these issues when they arise, we add randomness to the resource name

We should make sure tests are never "leaking".

Possible approaches:

- Before running the harness test, validate that all resources configured have a randomised name.
- Run the `terraform destroy` command even if a `terraform apply` failed
  - If the destroy failed, though, this might not help fix the issue

**Comment by RLRabinowitz** [comment]
Oh I missed that `defer`. Seems like that's not the reason for some resources not being removed, then.
We'd probably need to investigate that further next time

**Comment by RLRabinowitz** [comment]
I just figured that this issue also has another suggestion - To check for name randomness.
Seems like some of the issues we've gotten were due to some failed cleanup (not sure how), and no randomness in the resource name has caused the tests to always fail.

Not sure how feasible that is, but maybe it's the best bet we've got

**Comment by yaronya** [comment]
@RLRabinowitz can we be more specific on the required changes for this? I'd like to put it into work, if possible

**Comment by RLRabinowitz** [comment]
Every time we have a resource with a static `name`, we risk having harness tests leak and preventing all next harness tests from succeeding.

Today, our solution for that is to add randomness in `name`s, but we've had a ton of cases where we've missed that, and harness tests failed because of it

If we could have some guardrails here, forcing names to be randomised, that'd be great. 
Any other solution solving the pain I've mentioned above would also be great

**Comment by yaronya** [comment]
Since it's all terraform code, I'm not sure there's any native ability to terraform to assert those namings.

To me, it sounds like we'll need to parse the HCL files and make sure each `resource` has a randomized `name` attribute, but I'm not sure it worths the investment tho. WDYT?

**Comment by yaronya** [comment]
We've decided to drop this effort for now
