### ISSUE TITLE
Getting API_Secret from env0_api_key resources

### ISSUE THREAD

**Issue by mmclane** [env0/terraform-provider-env0#460]
There doesn't seem to be a way to get the env0_api_secret if you create the key with the terraform provider.  Am I missing something?

**Comment by omry-hay** [comment]
@mmclane yes, you are right, you should have a way to retrieve it as an output.
@TomerHeber let's fix this one, please.
It needs to behave like AWS IAM `aws_iam_access_key` - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key

This means the import can either be done only if supplying the secret, and we shouldn't make it available through the data resource.
