### ISSUE TITLE
Add `outputs` attribute to the environment resources

### ISSUE THREAD

**Issue by omry-hay** [env0/terraform-provider-env0#465]
In certain cases, you would like to pass outputs from one environment to another environment as an input.
The  `env0_environment` resource should have the `outputs` data of the environment as an output, both in the resource and the data resource.
Pay attention that this might be empty if the environment is still in progress.

**Comment by yaronya** [comment]
@omry-hay how that differs from simply accessing `env0_environment.X.name` or any other attribute? Is there a reasoning behind having a dedicated `outputs` attribute?

**Comment by omry-hay** [comment]
@yaronya the output attribute of the environment is the output of the Terraform run of that environment and not the attribute on the environment resource.
This way, instead of importing the entire Terraform state of that environment as a data resource, you can use the env0 environment resource to get the outputs of the latest run. 

This is similar to what TFE has - https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/outputs
