### ISSUE TITLE
CD and PR plan settings on environment are not applied correctly

### ISSUE THREAD

**Issue by omry-hay** [env0/terraform-provider-env0#471]
Step to reproduce:
1. Create a new project.
2. Go to the project settings  -> policies.
3. Make sure that in the Continuous Deployment section both `Run Terraform plan on Pull Requests` and `Redeploy on every push` are enabled.
4. Create a new environment using the terraform provider and set the `deploy_on_push` to false and `run_plan_on_pull_requests ` to false.
5. Once the environment is created, run another `terraform plan` without changing anything. 
6. The plan will say it's going to change the `deploy_on_push` and the `run_plan_on_pull_requests ` from `true` to `false
7. You can also check the UI and see that under the environment in the settings tab that both PR plan and CD are enabled.

**Comment by TomerHeber** [comment]
Caused by this issue in terraform:
https://github.com/hashicorp/terraform-plugin-sdk/issues/817

**Comment by TomerHeber** [comment]
https://github.com/hashicorp/terraform-plugin-sdk/pull/350

**Comment by TomerHeber** [comment]
https://github.com/hashicorp/terraform-plugin-sdk/pull/350
