### ISSUE TITLE
The environment configuration section is missing some attributes

### ISSUE THREAD

**Issue by omry-hay** [env0/terraform-provider-env0#472]
In the `configuration` section in the `env0_environment` resource, we are missing some attributes compared to the `env0_configuration_variable` resource. We are missing the following:

- `format`
- `enum`
- `is_read_only`
- `is_required`
- `regex`

**Comment by TomerHeber** [comment]
@omry-hay - I think format and enum are there.
They're just called: schema_enum and schema_format
