### ISSUE TITLE
Add unit tests for PR#37 (project data and resource)

### ISSUE THREAD

**Issue by roni-frantchi** [env0/terraform-provider-env0#49]
Merged #37 to resolve #21 - but no ut since we haven't merged in the testbed.
We should add a proper unit test once the testbed's in place

**Comment by roni-frantchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UT TF Provider - Description attribute for project resource and data types](https://trello.com/c/AWqHdmLz/3328-ut-tf-provider-description-attribute-for-project-resource-and-data-types)

**Comment by yaronya** [comment]
Project resource fixed in #70 
Project data source will be fixed by @avnerenv0 soon and this can be closed 🙏
