### ISSUE TITLE
v1.2.7 breaks terraform plan --target

### ISSUE THREAD

**Issue by mmclane** [env0/terraform-provider-env0#512]
I am currently using the v1.1.1 env0 provider.  Yesterday I started trying to use the v1.2.7 so that I can create an VCS environment but I am running into issues.  As a little bit of a background, I am working in a module with submodules that sets up all of our env0 environments.  The only other thing it might do is setup the drift detection on those environments.

Steps to reproduce:
- Using v1.1.1 I run a plan and I get no changes.
- I change my provider statements to version = ">= 1.1.1" to get the latest version and run terraform init --upgrade.  Terraform installs env0/env0 v1.2.7
- I run terraform plan again and now I have 4 to change.  It looks like it wants to reorder some of the env0_environments configuration values, but not all of them.  Not wanted to work through them all at once I decide to target an individual resource and change them one at a time.
- I run terraform plan --target '{{resource}}' and I get an error

```
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵
╷
│ Error: Failed to decode resource from state
│ 
│ Error decoding "{{a different resource}}" from previous state: unsupported attribute "template"
╵
Releasing state lock. This may take a few moments...

```
Its worth noting that the resource stated in the error is not the same resource that I am trying to target!  Its also worth noting that the resource stated in the error changes if I target something else.  Otherwise the error is the same.

If I run terraform plan  without the --target parameter it does successfully create a plan.

If I change my providers statement back to version = "1.1.1.1" and rerun terraform init --upgrade it fixes the issue and I can again run a plan with --target.

This makes me believe I should avoid v1.2.7

**Comment by TomerHeber** [comment]
Hi @mmclane 

Could you please share a minimal reproducible sample?
I will then try and reproduce it locally.

Thank you!

**Comment by mmclane** [comment]
I will have to see if I can create a minimal reproducible sample to share, that might take a bit.  I completely understand you need to repo it, I just need to figure out how much of my setup I have to remove to make that minimal and sharable.

**Comment by mmclane** [comment]
Here is my reproducible sample: https://github.com/mmclane/env-provider-issue-512

Note.. I have included a .terraform-version file so that your using the same version as I am.  I will do a little more testing to see if updating terraform makes a difference.  I believe I tested that yesterday but I want to make sure.

**Comment by TomerHeber** [comment]
@mmclane thank you for sending the instructions and sharing the reop. I followed your instructions and was able to reproduce the error.

I'll investigate.

**Comment by mmclane** [comment]
That seems to mitigate the issue indeed.

**Comment by TomerHeber** [comment]
@mmclane - thanks for confirming. I would guess the mitigation fixes some schema differences between the versions.
Would it be okay to close the issue?
