### ISSUE TITLE
Wait for environment to be destroyed

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#530]
When destroying an environment and a project together
The project will fail because the environment was not completely removed.

Please add a mechanism to wait for the enviroment's destroyed (or inactive) before archiving the project.

**Comment by yaronya** [comment]
That's correct. We removed it between major versions for a whole bunch of other reasons listed in #424 

Perhaps we can tackle it differently. We can either solve it only for destroy, or simply notice our users to use the `force_destroy` attribute of the project resource. @away168 WDYT?

**Comment by chpl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When canceling env deployment, redirect to templates page instead of the env](https://trello.com/c/ywiwMPEB/8256-when-canceling-env-deployment-redirect-to-templates-page-instead-of-the-env)

**Comment by away168** [comment]
how does the force_destroy for project resource work?  is it simply archiving the project, which could cause orphaned active environments.  e.g.  you destroy an environment and a project at the same time, but for whatever reason the environment fails to destroy, if the project is archived, it'll be difficult for the user to fix the environment.  If this is true, then I would vote to add the wait for destroy.

**Comment by yaronya** [comment]
> That's correct. We removed it between major versions for a whole bunch of other reasons listed in #424
> 
> Perhaps we can tackle it differently. We can either solve it only for destroy, or simply notice our users to use the `force_destroy` attribute of the project resource. @away168 WDYT?

Scratching my previous comment. I was referring to the relationship between an environment an its deployments in the provider.


So @TomerHeber, do you think we can add such flag for the `project` resource? It should poll on the `environments` API and wait for all environments to destroy, with a timeout of lets say... 10 minutes? Sounds legitimate?

**Comment by TomerHeber** [comment]
> > That's correct. We removed it between major versions for a whole bunch of other reasons listed in #424
> > Perhaps we can tackle it differently. We can either solve it only for destroy, or simply notice our users to use the `force_destroy` attribute of the project resource. @away168 WDYT?
> 
> Scratching my previous comment. I was referring to the relationship between an environment an its deployments in the provider.
> 
> So @TomerHeber, do you think we can add such flag for the `project` resource? It should poll on the `environments` API and wait for all environments to destroy, with a timeout of lets say... 10 minutes? Sounds legitimate?

@yaronya - sounds good to me.
