### ISSUE TITLE
Adding sub-environment workspace, revision and variables for workflow environments

### ISSUE THREAD

**Issue by eladmosh** [env0/terraform-provider-env0#536]
Hi @TomerHeber,
We are working on a new feature for our **workflow** environment.
For each workflow environment we want to be able to configure the following attributes for its sub-environments:
1. workspace names
2. revision
3. configuration variables

We added a new field for the environment creation endpoint `/environments/<environment id>` and the redeploy endpoint `/deployments/<deploy id>, called `subEnvironments`.

the  new environment resource should now look like this:

```terraform

resource "env0_environment" "example_with_sub_environments_configuration" {
  name        = "workflow environment with subenvironments"
  project_id  = data.env0_project.default_project.id
  template_id = data.env0_template.example.id
  sub_environment_configuration {
      alias = "sub_env1"
      revision = "sub_env1_branch"
      workspace = "workspace1"
      configuration {
          name          = "sub_env1_var1"
         type          = "environment"
         value         = "hello"
      }
      configuration {
         name          = "sub_env1_var2"
         type          = "environment"
         value         = "world"
      }
  }
  sub_environment_configuration {
        alias = "sub_env2"
        revision = "sub_env2_branch"
        workspace = "workspace2"
        configuration {
            name          = "sub_env2_var1"
           type          = "environment"
           value         = "hello"
        }
        configuration {
           name          = "sub_env2_var2"
           type          = "environment"
           value         = "world"
        }
    }
}
```

Where the `sub_environment_configuration.configuration` is the same type as `environment.configuration`.
We should aggregate all those `sub_environment_configuration`s into one `map[string]subEnvironment` where the `string` keys are the `sub_environment_configuration.name` and the `subEnvironment` value is:
```go
type SubEnvironment struct {
  revision                         string  `json:"revision,omitempty" tfschema:"revision"`
  workspace                    string  `json:"workspace,omitempty" tfschema:"workspace"`
  configurationChanges *configurationsChanges `json:"configurationChanges,omitempty" tfschema:"-"`
}
```

This new `sub_environment_configuration` map should be added to the `DeployRequest`  as:
```typescript
SubEnvironments map[string]subEnvironment `json:"subEnvironments,omitempty"`
```

**Note**: all those changes only apply for workflow environments, meaning environments that were created from a template of type `workflow`

It's a big change so let me know of you have any question.

**Comment by TomerHeber** [comment]
@eladmosh is this feature ready?
Is there an API for it?

**Comment by yaronya** [comment]
@TomerHeber not yet, I'll assign it to you once this is fully ready

**Comment by eladmosh** [comment]
@TomerHeber regarding the api, we only changes the existing `create` and `deploy` endpoints.
`/environments/<environment id>` and `/deployments/<deploy id>`

**Comment by TomerHeber** [comment]
@yaronya - is this ready now?

**Comment by eladmosh** [comment]
@TomerHeber the API is ready, send you the links to the corresponding  endpoints
