### ISSUE TITLE
Using git `token_id` on Templates always assumes GitLab

### ISSUE THREAD

**Issue by roni-frantchi** [env0/terraform-provider-env0#545]
Git tokens in env0 can be used to integrate with "Other VCS", GitLab, and soon Azure DevOps.  
Setting `token_id` on this provider [always assumes](https://github.com/env0/terraform-provider-env0/blob/75af2bebbc1b57400acfa1d6d68e54c577b7fd86/env0/resource_template.go#L342) we're using Gitlab, causing the request to fail.  

# Steps to reproduce:
Apply:  
```terraform
resource "env0_environment" "foobar" { #could also be just a template_resource
  name        = "foobar"
  project_id  = data.env0_project.default_project.id
  
  without_template_settings {
    repository = "https://github.com/env0/templates"
    token_id = "68ba48c9-ec6e-4177-a130-e6f3ffb02f9b"
  }
}
```  

This will fail with:  
```
│ Error: could not update template: 400 Bad Request: You have no access to that repository
```  

Examining the request made by the client shows the template is marked as **gitlab** despite not setting `isGitlab: true`

**Comment by Wassap124** [comment]
This happens again
