### ISSUE TITLE
"Infinite" isn't a valid value for the max/default TTL Policies API

### ISSUE THREAD

**Issue by roni-frantchi** [env0/terraform-provider-env0#549]
**_Unfortunately_**, `"Infinite"` is **not** a supported value for max/default TTL on Policies API.  
An explicit `null` is used to denote there is **no** TTL restriction should be applied.  

To reproduce:  

```terraform
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
      version = "1.2.11"
    }
  }
}

provider "env0" {
  api_key      = "xxxx"
  api_secret   = "yyy"
}

resource "env0_project_policy" "example" {
  project_id                    = data.env0_project.default_project.id
  number_of_environments        = null
  number_of_environments_total  = null
  max_ttl                       = "Infinite"  # <--- this will soon be blocked by our API as it is not a supported value, explicit `null` is
  default_ttl                   = "1-w"
}

data "env0_project" "default_project" {
  name = "My First Project"
}

```  

### DoD  
Either the provider map `"Infinite"` to `null` (and vice-versa on `data` and verification) on both this resource and `organization_policy`, or drop `"Infinite"` as valid value altogether as it doesn't work.  
Note there's an integration test to be changed as well

**Comment by roni-frantchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project TTL not adopted by env when set by TF Provider](https://trello.com/c/RemGrqPr/8076-project-ttl-not-adopted-by-env-when-set-by-tf-provider)

**Comment by TomerHeber** [comment]
@roni-frantchi 

This should have been fixed in a previous PR.
"Infinite" should not be sent. What kind of error are you observing?

https://github.com/env0/terraform-provider-env0/pull/527

**Comment by yaronya** [comment]
It's not supported for this API. We accidentally allowed it. 
It's now disallowed so we need to remove it from the provider (or make sure `null` is sent)

**Comment by TomerHeber** [comment]
@yaronya and @roni-frantchi - AFAIK null is sent.
Is it not the case?

**Comment by roni-frantchi** [comment]
@TomerHeber I tested it with the latest provider version ~4 days ago, `"Infinite"` was sent.  
Also - I can't merge my PR that adds backend API schema validation to the request, because the provider tests then fail, as it seems to send `"Infinite` and my change protects the backend against it
