### ISSUE TITLE
Custom Flow Support

### ISSUE THREAD

**Issue by yarivg** [env0/terraform-provider-env0#550]
add support for custom flow configuration

```
resource "env0_custom_flow" "example" {
  name                   = "example"
  repository             = "example"
  path                   = "example"
  revision               = "example"
  token_id               = 0
  ssh_keys               = []
  gitlab_project_id      = 0
  github_installation_id = 0
  bitbucket_client_key   = 0
  is_bitbucket_server    = "true/false"
  is_gitlab_enterprise   = "true/false"
  is_github_enterprise   = "true/false"
  is_git_lab             = "true/false"
  is_azure_devOps        = "true/false"
}

resource "env0_custom_flow_assignment" "assignment_example" {
  depends_on = [env0_custom_flow.example]
  scope      = "PROJECT"
  scopeId    = "example"
  templateId = env0_custom_flow.example.id
}
```

**Custom Flow API**
- [Create](https://developer.env0.com/docs/api/b0edc780360d8-create-a-custom-flow)
- [Update](https://developer.env0.com/docs/api/5c9f86bda309b-update-a-custom-flow)
- [Delete](https://developer.env0.com/docs/api/9bf511118e20d-delete-a-custom-flow)
- [Assign](https://developer.env0.com/docs/api/8314044c581b9-assign-custom-flow)
- [Unassign](https://developer.env0.com/docs/api/7e931f6b0acdf-unassign-custom-flow)

**Comment by yaronya** [comment]
@yarivg is is something you'll be implementing or should @TomerHeber address it?

**Comment by yarivg** [comment]
Tomer

**Comment by yarivg** [comment]
> @yarivg is it something you'll be implementing or should @TomerHeber address it?

Tomer

**Comment by TomerHeber** [comment]
@yaronya  @yarivg I will need more information before I proceed.

The API for creation is as follows:
https://developer.env0.com/docs/api/b0edc780360d8-create-a-custom-flow

I need a list of all the constraints and invalid/valid use-case, so I can "block"/"allow" them in the provider.

Thanks!

**Comment by yarivg** [comment]
> @yaronya @yarivg I will need more information before I proceed.
> 
> The API for creation is as follows: https://developer.env0.com/docs/api/b0edc780360d8-create-a-custom-flow
> 
> I need a list of all the constraints and invalid/valid use-case, so I can "block"/"allow" them in the provider.
> 
> Thanks!

Answered in slack.
