### ISSUE TITLE
workflow trigger new resources

### ISSUE THREAD

**Issue by samuel-br** [env0/terraform-provider-env0#580]
We need to add another resource to WorkFlow-Trigger, our workflow trigger today is calling api which update the triggers by overriding the former list, for example - former list = [1,2,3,4] => update list with(5) => new trigger list = [5].

We have users who manage multiple stacks with triggers from the same environment, so this creates concurrency issues for them.

We created new endpoints for "atmoic" updates to the triggers list, and we should create a *new resource* called `workflow_trigger` which will represent a single trigger. 

The relevant endpoints are 
[Subscribe environments as workflow-trigger](https://docs.env0.com/reference/environments-subscribe-downstream-environments)
[Unsubscribe environments as workflow-trigger](https://docs.env0.com/reference/environments-unsubscribe-downstream-environments)

**Comment by avnerenv0** [comment]
@TomerHeber let me know if you have any questions on the above.
