### ISSUE TITLE
Add new integrated vcs info to env0_environment data source 

### ISSUE THREAD

**Issue by eladmosh** [env0/terraform-provider-env0#586]
#### Why?

env0 Provider users that want to create an [env0_template](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/template) or a vcs [env0_environment](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/environment#without_template_settings) without a template needs to have a [token_id](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/environment#token_id).
So for private repo templates/environments we can use the [env0_git_token](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/git_token) data source to fetch the token_id and use it in our `env0_template`/`env0_environment`.
But what if our `env0_template`/`env0_environment` vcs is our integrated github/gitlab/bitbucket or Azure DevOps? Those tokens are different than the git tokens and are created internally by env0.
We want to let the provider user get those tokens to create his `env0_template`/`env0_environment` resources
#### How?
We should add the following attributes to `env0_environment` data:

1. bitbucket_client_key  - for BitBucket
2. github_installation_id - for Github
3. gitlab_project_id  - for Gitlab
4. token_id  - for Gitlab and Azure DevOps

All the info is not supposed to be a big deal since we already have them in `env0_template` `data` so we just need to get the environment's template_id and get this info the same way we get it for `env0_template`.

Let me know if you have any question.

**Comment by RLRabinowitz** [comment]
The usage of this is mainly to be able to attach an existing Azure DevOps or Gitlab token to an env0 template

**Comment by RLRabinowitz** [comment]
Actually, this might not be necessary. Azure DevOps and Gitlab tokens are created by env0 on template creation.
So, a user can simply find such a token by using an `env0_template` data source to get the `token_id`

**Comment by eladmosh** [comment]
@RLRabinowitz we also want to cover no-template environment so we decided to add the required info to `env0_environment`.
The user will create a "master" environment and use this environment data in the provider to use it's newly added vcs credentials, just like the template approach you suggested.
WDYT?

**Comment by TomerHeber** [comment]
@eladmosh - let me know when this is triaged, and I can start working on it.

**Comment by TomerHeber** [comment]
*assign to me when it is ready.

**Comment by avnerenv0** [comment]
@RLRabinowitz the gap is in "VCS environments" - so using an `env0_template` is very unintuitive for our users - they don't know there is a template, they don't see it in the UI.

We want to mirror the format of the `env0_environment` resource in the same _data_ resource.

What's currently missing is the `without_template_settings` attributes, or more specifically - the ones that @eladmosh wrote - `bitbucket_client_key`, `github_installation_id`, `gitlab_project_id, and `token_id`.

**Comment by eladmosh** [comment]
In a matter of fact this got bumped up due to some important clients experiencing this issue so we'll appreciate if you could prioritize it.
