### ISSUE TITLE
Resource env0_gcp_credentials is unclear WRT self-hosed agents

### ISSUE THREAD

**Issue by rbounds** [env0/terraform-provider-env0#590]
the gcp_credentials resource docs has a required filed `service_account_key` with the description of `the gcp service account key` but with self-hosted agents you aren't allowed to store sensitive data so it is unclear if this should a reference to pointing to third party secrets ie {gcp:my_key} or if I should be adding the key directly.  It would be good to word the docs in such a way as to remove the ambiguity.

**Comment by yaronya** [comment]
Hi @rbounds 
Thanks for the feedback.
We'll take a look and come up with a better description there.
