### ISSUE TITLE
Stop sending `external_id` for `env0_aws_credentials` resource

### ISSUE THREAD

**Issue by Wassap124** [env0/terraform-provider-env0#591]
Hey hey!

for security reasons, the external_id for `env0_aws_credentials` is now resolved on the backend, so there no reason to support it anymore.

Please remove it from the resource entirely

**Comment by avnerenv0** [comment]
Hi @TomerHeber 
We still want this and are planning to release it on March 12th.
I think PR #593 is still relevant - we would want to remove the field from the provider at that time. 
Sounds OK ?

**Comment by TomerHeber** [comment]
@avnerenv0 - sounds good!
Please update me one it's deployed. I will then make the changes in the provider as well.
(At the moment users receive a deprecated message).
