### ISSUE TITLE
Add env0 to error output when credentials are missing when using the provider locally.

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#596]
qualify of life fix. 🙏  

helps me identify which provider is causing the error, when using multiple providers.

**Comment by TomerHeber** [comment]
@away168 - I will need more details. What is the current output? What would be the new output?

**Comment by TomerHeber** [comment]
@yaronya - this message comes from the terraform SDK (enforcing the schema).
Unsure if there's much we can do. I'll check the SDK source code... maybe I can override something in there...

**Comment by TomerHeber** [comment]
In addition, I need an output example.

E.g. this is my output:
```
(.venv) ➜  tf git:(chore-deprecate-external_id-#593) ✗ terraform apply      
provider.env0.api_secret
  env0 API secret. This can also be set via the ENV0_API_SECRET environment variable.

  Enter a value: 

╷
│ Error: 401 Unauthorized: {"message":"Unauthorized"}
│ 
│   with provider["terraform.env0.com/local/env0"],
│   on <input-prompt> line 1:
│   (source code not available)
│ 
╵

```

**Comment by TomerHeber** [comment]
Requirements are unclear.
I will close for now and will re-open if needed.
