### ISSUE TITLE
Support personal API keys

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#608]
issue: tfprovider complains when using personal api keys that has access to multiple organizations. 

```
% terraform plan
╷
│ Error: server responded with too many organizations
│ 
│   with provider["registry.terraform.io/env0/env0"],
│   on providers.tf line 2, in provider "env0":
│    2: provider "env0" {
│ 
╵
```

request: 
to add an optional `organization_id` parameter for the provider configuration

**Comment by yaronya** [comment]
@TomerHeber let's make sure to treat the new `organization_id` param **only** when there are more than 1 organization for given api key. I think docs should also say that.
