### ISSUE TITLE
Resources in IT don't have unique names

### ISSUE THREAD

**Issue by sagilaufer1992** [env0/terraform-provider-env0#614]
The IT are built in such a way that they create resources and remove them once they are finished. an error during those may leave some resources behind.
Unique names allow us to rerun tests without the trouble of names colliding between runs.
Make sure all the resources have unique names when it comes to IT.

**Comment by sagilaufer1992** [comment]
@yaronya mind adding a few examples you found?

**Comment by yaronya** [comment]
@TomerHeber please go over and check those, I've seen a few templates that are not unique, for example
But I bet there are also other resources

**Comment by TomerHeber** [comment]
@yaronya - I will do another sweep.

**Comment by TomerHeber** [comment]
@yaronya - I couldn't find any use-cases.
Please review. It could be old resources.

**Comment by TomerHeber** [comment]
@yaronya - may I close this?

**Comment by TomerHeber** [comment]
Reviewed all tests. None of them have this issue.
