### ISSUE TITLE
 Optional attribute auto_deploy_by_custom_glob trigger resource update

### ISSUE THREAD

**Issue by Qbandev** [env0/terraform-provider-env0#624]
We are deploying the following env0 environment resources in a module using version `"1.3.14"` of the env0 provider :

```HCL
resource "env0_environment" "base" {
  name                             = local.project_name
  workspace                        = local.project_name
  project_id                       = local.project_id
  is_remote_backend                = true 
  force_destroy                    = true
  run_plan_on_pull_requests        = true
  approve_plan_automatically       = true
  deploy_on_push                   = true
  auto_deploy_on_path_changes_only = true
  without_template_settings {
    github_installation_id = local.github_installation_id 
    path                   = local.path
    type                   = "terraform"
    repository             = local.url
    description            = local.project_name
    terraform_version      = "RESOLVE_FROM_TERRAFORM_CODE"
  }
  lifecycle {
    ignore_changes = [
      workspace,
    ]
  }
}
```
And every time we run a `terraform plan`  we get the following upcoming changes:

```HCL
  # module.env0_projects[0].env0_environment.base[0] will be updated in-place
  ~ resource "env0_environment" "base" {
      - auto_deploy_by_custom_glob       = ".some_path/**" -> null
        id                               = "some_id"
        name                             = "some_name"
        # (15 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

We are not expecting this change to occur as we didn’t configure the [optional attribute](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/environment#auto_deploy_by_custom_glob) `auto_deploy_by_custom_glob`

**Comment by TomerHeber** [comment]
@Qbandev - this means that someone configured in the UI `".some_path/**"`
I recommend removing it from the UI or adding it to the terraform configuration.

Unless there's something I'm missing here?

**Comment by Qbandev** [comment]
> 

Hi @TomerHeber, 
The path `- auto_deploy_by_custom_glob       = ".some_path/**" -> null` is not configured in the UI. I just double-checked that no one manually changed the environment settings in the env0 UI.
The configuration in the UI is `Run On: Changes on Template Directory files` and [according to the documentation](https://docs.env0.com/docs/continuous-deployment#existing-environment)  "_your environment will redeploy on every push which the push contains file changes under Terraform Folder_" that is the same we are sending in the module:
```hcl
auto_deploy_on_path_changes_only = true
```

**Comment by yaronya** [comment]
Hi @Qbandev 
Thanks for reaching out on this one.

I'm 99% sure that the `.some_path/**` string is not something that is set by env0's backend, yet there might be an issue where there's a wrong read being done by the provider, or something to do with how the glob pattern is saved.

To validate that, can I kindly ask you to:
1. Validate that this is consistent and still happens.
2. Send me the organization and environment names, please.

🙏

**Comment by Qbandev** [comment]
Hi @yaronya 

I found someone in the team doing tests in the project was setting it manually and forgot to remove it later, as  @TomerHeber suspected.

Thanks so much for your help! 🙏
