### ISSUE TITLE
Add support to map VCS alias to user

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#629]
Please add support for this API 

https://docs.env0.com/reference/users-update-vcs-provider-user-mappings

env0 docs:
https://docs.env0.com/changelog/pr-comments-plan-and-apply-role-based-access

**Comment by yaronya** [comment]
@TomerHeber why is this one blocked?

**Comment by TomerHeber** [comment]
@yaronya - see https://env0.slack.com/archives/C01QBBEGBEH/p1681488392573519
