### ISSUE TITLE
ability to filter for parent project name in data project resource

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#630]
example: 
I have the following project structure

"product-a" > "dev"
                     > "stage"
                     > "prod"
"product-b" > "dev"
                     > "stage"
                     > "prod"
                     
The data resource to find "product-a/dev" project

so something like adding a parent project filter would be great.

**Comment by yaronya** [comment]
Hi @away168 

Could you explain a bit further what exactly you're trying to achieve?

**Comment by away168** [comment]
so basically the human query: 

get me 'dev' project in parent project 'product-a'

the data resource probably would look something like this:

```
data "env0_project" "sub_project" {
  name = "dev"

  filter { 
    parent_project_name = "project-a"  // or parent_project_regex = "^project-a"
  }
}
```

**Comment by yaronya** [comment]
What happens today when you do?
```
data "env0_project" "sub_project" {
  name = "dev"
```

Would it fail with "multiple projects found" error?

If this is the case, we could simply add a `parent_project_name` attribute (no need for regex I suppose)

**Comment by away168** [comment]
Yes, it fails with "Error: multiple Projects for name: Dev. Use ID instead"

**Comment by TomerHeber** [comment]
@yaronya @away168 - have we concluded what's needed?
Would parent_project_name suffice without a filter?

**Comment by yaronya** [comment]
Yes, let's use the `parent_project_name` as an optional attribute

**Comment by TomerHeber** [comment]
@away168 - happy to change if this is preferred. Let me know...
