### ISSUE TITLE
Add Error property in latestDeploymentLog

### ISSUE THREAD

**Issue by ezeql** [env0/terraform-provider-env0#641]
Hi Env0!

https://docs.env0.com/reference/environments-find-all output contains `latestDeploymentLog`. `latestDeploymentLog` also contains `error`. 

Please add support for `error` in Go. 

https://github.com/env0/terraform-provider-env0/blob/main/client/environment.go#L86

Thank you.

**Comment by TomerHeber** [comment]
Hi @ezeql ,

QQ: is it just required for the API (using golang)? Or is it also needed in the terraform schema?

**Comment by ezeql** [comment]
Hi @TomerHeber 

Just the client, in Go. We don't need it exposed In terraform

Thank you in advance!
