### ISSUE TITLE
env0 TF Resources Default Values

### ISSUE THREAD

**Issue by AlexAtkinson** [env0/terraform-provider-env0#646]
Please add default values for _all_ env0 terraform provider resource arguments.

For example, [force_destroy](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/project#force_destroy) does not indicate the default value if left unspecified.

A fix for that example would result in:

- [force_destroy](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/project#force_destroy) (Boolean) Destroy the project even when environments exist. Defaults to `true`.

> NOTE specifically that I DO NOT KNOW the default value. That's just an example.

**Comment by TomerHeber** [comment]
Hi @AlexAtkinson ,

This is a fair ask.

Unfortunately, adding a default value is not always backward compatible.
At the end of the day, the Terraform SDK converts the configurations to API requests.

You can assume the following regarding the API calls if the default isn't set:
boolean: false or nothing in the json (undefined).
string: "" or nothing in the json (undefined).
int: 0 or nothing in the json (undefined).

Note: sometimes the behavior varies between 'false' or undefined.

I hope this information helps. If there are specific use cases that it's still ambiguous, please let me know.

**Comment by AlexAtkinson** [comment]
If default values, or even argument presence is going to change from version to version, I highly recommend utilizing readme.com's [documentation version feature](https://docs.readme.com/main/docs/versions), and start including this information.
Guessing, or maintaining training on assumptions established by the product devs to use the tool is undesirable.

Simply starting by updating the current version docs and persisting this detail going forward would be the easiest for you.
Ideally default values/behaviors that change would issue a large notice for n versions until the change is well baked.

**Comment by yaronya** [comment]
Thanks for the feedback @AlexAtkinson 
We'll consider it for our future roadmap when implementing new capabilities to the provider.
