### ISSUE TITLE
Configuration Variable Value Only Argument

### ISSUE THREAD

**Issue by AlexAtkinson** [env0/terraform-provider-env0#648]
Env0 offers variable inheritance as a feature. Because these variables are set globally at the organization level, it is desirable to have a Terraform provider facility for setting the value of an existing variable for a project.

Perhaps update configuration variable to take an argument indicating it's setting the value of an existing resource, rather than creating the resource.
https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable

Attempting to set the value for an inherited variable results in the expected:
```
╷
│ Error: could not update configurationVariable: 400 Bad Request: A property named "TF_VAR_WORKLOAD_ENVIRONMENT" already exists for organization "foo" on scope "PROJECT"  scopeId foo
│ 
│   with env0_configuration_variable.root_project_TF_VAR_WORKLOAD_ENVIRONMENT,
│   on project-variables.tf line 34, in resource "env0_configuration_variable" "root_project_TF_VAR_WORKLOAD_ENVIRONMENT":
│   34: resource "env0_configuration_variable" "root_project_TF_VAR_WORKLOAD_ENVIRONMENT" {
│ 
```

**Comment by AlexAtkinson** [comment]
After some poking at the api and inspecting the POSTs out of the UI, it appears the API requires the 'id' field to be provided to be able to update a variable. I suggest that this is undesirable and unnecessary.

- unnecessary because through the inclusion of environmentId, and projectId fields, the api is already informed of where to place the var (scope), and depending on the presence of a var matchin the  'name' attribute, it can determine it's action.
- undesirable because by requiring the ID, the api call is no longer the same for create/update...

If it is desired to require the workflow depend on a different call to distinguish between create/update actions, relying on the [HTTP Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods), specifically PUT/PATCH methods, is a good way to do this. Additionally, relying on the method for informing of the action will allow much more concise, easy to understand and implement code. See the [Marathon](http://mesosphere.github.io/marathon/api-console/index.html) project for a top-shelf exmaple.

Additionally, please add some information to the api docs about what scope ID is. It appears that it can be either GLOBAL, a project, or environment id. This is a bit unintuitive and redundant, though, considering the scope narrowing effect of the environmentId, and projectId fields as outlined in the [provider docs](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable)... Previously mentioned.

**Comment by AlexAtkinson** [comment]
I'll be working around this issue by running a bash script once the project is created that gets the var ids. Unfortunately the [env0_configuration_variable](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable) resource doesn't have an argument for the variable id, which is needed to update the value of a pre-existing variable (if it depends on [this api endpoint](https://docs.env0.com/reference/configuration-create-or-update-variable)).
_Please add this argument._

Until then, I'll be using bash to update the values.

**Comment by yaronya** [comment]
Hi @AlexAtkinson 
Thanks for the valued feedback and apologies for the late response

I'll pass all your legitimate suggestions regarding the confusing configuration variables API to the dev team, this is indeed a bit out of standard and not-so-easy to understand

Regarding adding the `id` attribute to the configuration variable resource - when you mention _pre-existing_, do you mean that the variable that you wish to update is not managed by TF (and is not in its state)?

**Comment by yaronya** [comment]
I see your point, thanks for sharing.

@TomerHeber do you think we could add the `id` as a valid input? The API supports this value, and when passed - treats the request as `UPDATE`, and when not passed - treats it as `CREATE`

**Comment by TomerHeber** [comment]
@AlexAtkinson @yaronya - I will look into it.

**Comment by TomerHeber** [comment]
@AlexAtkinson @yaronya 

Wouldn't `import` be enough?

https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable#import

**Comment by mgm-brandt** [comment]
> @AlexAtkinson @yaronya
> 
> Wouldn't `import` be enough?
> 
> https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable#import

The provider doesn't support import in some capacity it looks like:

```
╷
│ Error: resource env0_team_project_assignment doesn't support import
│ 
│ 
╵
```

I created https://github.com/env0/terraform-provider-env0/issues/677 for the same.

**Comment by yaronya** [comment]
Hey @mgm-brandt 
#677 is merged

Please let us known if it resolve you issues, and if it does - feel free to close this GH issue 😃
