### ISSUE TITLE
Resync Terraform Registry after release build is complete

### ISSUE THREAD

**Issue by avnerenv0** [env0/terraform-provider-env0#65]
When we release there is a github action that builds all the binaries.
But the TF Registry will pickup on the release too soon and we get

` Could not find all platform assets for this release yet (0.0.5) — 2 minutes ago `

Then we need to manually re-sync it (from the registry UI)

We should add an API call in the `release` flow to do that when the binaries are ready.

**Comment by eranelbaz** [comment]
@avnerenv0 this one is still an issue?

**Comment by avnerenv0** [comment]
As far as i know it's still an issue.

**Comment by avnerenv0** [comment]
AFAICT - TF registry doesn't have an endpoint for re-syncing the releases, it's only available from the UI
We can copy the cookie and hope it doesn't expire :man-shrugging::skin-tone-3:

Alternatively we can try to generate the binary assets on a "draft" release and then publish it , so maybe TFREG will pick it up correctly the first time
No idea if/how that can work

BTW the 'settings' button in the TFREG UI doesn't always work for me also - needs a refresh sometimes

**Comment by avnerenv0** [comment]
Possibly - So we can probably have the go-releaser just build the binaries everytime a draft is updated

**Comment by yaronya** [comment]
@GiliFaroEnv0 what's the status of this one?

**Comment by GiliFaroEnv0** [comment]
Solved by #228
