### ISSUE TITLE
Add support for `isRemoteBackend` for workflows

### ISSUE THREAD

**Issue by sagilaufer1992** [env0/terraform-provider-env0#656]
recently the option for declaring workflows as `remote-backend` was introduced.
the outcome is that every `terraform` sub environment is also `remote-backend`.

the provider should enable creating workflows that are `remote-backend` correctly:
- must be given `workspace` name
- duplicate `workspace` names of sub environments are not allowed (as they are `remote-backend`
- other constraints for `workspaces` are also in place - every template has a single environment with said workspace
- the constraints are validated in the BE as well, whatever can be validated in the provider prior to sending request is welcomed

**Comment by TomerHeber** [comment]
Closing this one.
Will handle it in https://github.com/env0/terraform-provider-env0/issues/662
