### ISSUE TITLE
Do not send terraformVersion unused field

### ISSUE THREAD

**Issue by tomporat247** [env0/terraform-provider-env0#659]
## Problem Overview
Our API is very forgiving in this matter, if you pass the terraform version field while you are in pulumi for example it doesn't have any effect - it's just not being used.

Theoretically you can send `terraformVersion` and `plulumiVersion` at the same request and env0 will accept it and just not use them.
However we shouldn't do that as:
1. That data can confuse us while we are debugging
2. Generally you want to avoid sending wrong data even when unused
3. This can create a bug if someone will introduce a new code that assumes stuff based on those variables (and logically he will be correct)

## Expected Solution
Do not send incorrect unused fields.
`terraformVersion` should not be sent for non terraform/terragrunt templates.

I guess there are more cases which we should fix too, so if you can think of some please fix them as well.

**Comment by yaronya** [comment]
Hey @TomerHeber WDYT about this one? is it clear enough?

**Comment by TomerHeber** [comment]
@yaronya - It would be better to define all use-cases.

I'll fix this:
`terraformVersion should not be sent for non terraform/terragrunt templates.`

But would be good to know the other use-cases.

**Comment by yaronya** [comment]
Let's focus on this one and that would cap this issue.
We'll create follow up issues for any other field
