### ISSUE TITLE
Provider Documentation Alignment With Terraform Verbage

### ISSUE THREAD

**Issue by AlexAtkinson** [env0/terraform-provider-env0#661]
Please align verbage in docs with terraform, specifically for 'input' and 'output'.
Currently the Env0 provider docs are unclear.

For example:
The [Template Project Assignment](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/template_project_assignment) doc shows retrieving a projectId by the project data source, but the [project data source doc](https://registry.terraform.io/providers/env0/env0/latest/docs/data-sources/project) doesn't have any 'id' output... 

Suggested Structure:

- Inputs
  - Required
    - foo
  - Optional
    - bar
- Outputs
  - foo
  - bar

Ideally the provider docs would be generated from your code base to avoid scenarios such as the above where the 'id' output field is absent... Or does it not exist, and the second doc is right? IDK atm.

**Comment by yaronya** [comment]
Hi @AlexAtkinson 

> Ideally the provider docs would be generated from your code base to avoid scenarios such as the above where the 'id' output field is absent

This is correct, and is handled by the TF core framework that reads the code and generates this information. 
Do you find it misleading that the `id` attribute is under the "Optional" section of [these docs](https://registry.terraform.io/providers/env0/env0/latest/docs/data-sources/project)?
