### ISSUE TITLE
`env0_team_project_assignment` doesn't support import

### ISSUE THREAD

**Issue by mgm-brandt** [env0/terraform-provider-env0#677]
When attempting import with `1.4.9`:
`
╷
│ Error: resource env0_team_project_assignment doesn't support import
│ 
│ 
╵
`

To support import: https://developer.hashicorp.com/terraform/tutorials/providers/provider-import?in=terraform%2Fproviders#implement-import

**Comment by yaronya** [comment]
Thanks for the feedback @mgm-brandt 
We'll put it in our ongoing issues list for it to resolve soon 😄

**Comment by TomerHeber** [comment]
@mgm-brandt - what kind of import are you looking for?
Based on the project_id and team_id pair?

**Comment by mgm-brandt** [comment]
I was looking to import the existing team project assignments which were setup in a separate state with a lineage issue. I had the ADDR and ID from the other state, but couldn't import. I ended up running with the new state and resolved the discrepancy.

**Comment by mgm-brandt** [comment]
I'm wondering if other resource types are import capable, I've not tried with projects, etc... where it would be more important.

**Comment by TomerHeber** [comment]
@mgm-brandt - most resources have an import.
Assignments generally do not have an import.

If there is a specific resource where you need an import, let me know.

Back to my question for env0_team_project_assignment in case you still require an important, it would be the pair "team_id_project_id" - would that suffice for your requirements?

**Comment by mgm-brandt** [comment]
Yeah that sounds good.

**Comment by TomerHeber** [comment]
@mgm-brandt - thank you for confirming. I will add it soon.
