### ISSUE TITLE
`env0_azure_cost_credentials` Update Credentials Instead of Replace

### ISSUE THREAD

**Issue by mgm-brandt** [env0/terraform-provider-env0#678]
Using provider `1.4.9`.

It'd be good to update credentials with a new secret instead of replace, example:

```
# module.env0-credentials.env0_azure_cost_credentials.default["###"] must be replaced
-/+ resource "env0_azure_cost_credentials" "default" {
      ~ client_id       = (sensitive value) # forces replacement
      ~ client_secret   = (sensitive value) # forces replacement
      ~ id              = "###" -> (known after apply)
        name            = "###"
        # (2 unchanged attributes hidden)
    }
```

I have a separate terraform state to manage projects and their cost credential associations, etc.., so there's a cross run dependency now on this when the credential is updated. I can accomodate this with the env0 workflow trigger as a work around.

**Comment by yaronya** [comment]
Thanks for the feedback @mgm-brandt 
This indeed can be done using [this API](https://docs.env0.com/reference/configuration-update-credential)

We'll make sure to add support soon

**Comment by TomerHeber** [comment]
Hi @mgm-brandt - I would like to understand your use-case a little better.
When you update the credentials - are both the secret and client_id updated? Any other fields you plan to update?
(or does the client_id remain the same?)

**Comment by TomerHeber** [comment]
Hi @mgm-brandt ,

Quick reminder on my question above. Thank you!

**Comment by yaronya** [comment]
@TomerHeber it's relevant for all attributes - `client_id`, `client_secert`, `subscription_id` and `tenant_id`

We probably need to do the same for all other credentials - this ability was added in UI but not in TF provider. I'll open another issue for it.
