### ISSUE TITLE
Cannot create env0_user_team_assignment: validation error

### ISSUE THREAD

**Issue by adelinn** [env0/terraform-provider-env0#681]
My userId contains an `_` in it and for that reason I'm unable to create an env0_user_team_assignment resource.
The following function fails because two underlines are present in the string.
https://github.com/env0/terraform-provider-env0/blob/9db74b01fa8a46142d8768195a2303fa64c4144c/env0/resource_user_team_assignment.go#L36-L45

**Comment by TomerHeber** [comment]
Hi @adelinn ,

I'm more curios than anything:
How was that user created? could you share the ID?

**Comment by TomerHeber** [comment]
@adelinn - thank you. I will work on a fix.
