### ISSUE TITLE
Harness tests don't show expected "integration tests" mode logs

### ISSUE THREAD

**Issue by yaronya** [env0/terraform-provider-env0#688]
Refers to the code added in #578 
If you run harness tests in GH action while turning `INTEGRATION_TEST` mode on - you'd see only the logs performed by the `harness.go` file and wouldn't see any other logs (for example, the ones that are performed by `provider.go`)

It may have to do with the fact that the harness tests and TF aren't running on the same process.

**Comment by TomerHeber** [comment]
@yaronya - I think this was always the case.
Only on failure would it show logs.

Is the ask to change that?

**Comment by TomerHeber** [comment]
If yes... which log level would we like to show?

**Comment by yaronya** [comment]
We haven't seen any logs - for either failure or non-failure

I think we'd like to always see these logs in case `INTEGRATION_TESTS` is turned on - we get failures and we don't know if the test retried or not. 
Let's start with `INFO` log level - we could always change that later on.
