### ISSUE TITLE
env0_git_token recreating in every tf apply

### ISSUE THREAD

**Issue by diego7marques** [env0/terraform-provider-env0#707]
**Describe the bug**
The env0_git_token resource recreates the Git token on each run, even if the value does not change.

**To Reproduce**
Run terraform apply with the following resource:

resource "env0_git_token" "token" {
  name  = "git_token"
  value = <token_value>
}

After the resource is created, run terraform apply again.

**Expected behavior**
The apply must indicate that there is no changes to be applied.

**Provider Version**
1.14.15

**Screenshots**
![image](https://github.com/env0/terraform-provider-env0/assets/49801014/ccd9f8a9-0df1-43c8-8623-0fadc061276f)

**Additional context**

**Comment by TomerHeber** [comment]
Hi @diego7marques - thank you for reporting the issue.
I have created a PR to fix the issue and will deploy it soon.

**Comment by TomerHeber** [comment]
Hi @diego7marques - I've released a new version containing a fix for the issue.
