### ISSUE TITLE
Unable to unset auto_deploy_by_custom_glob property of environment resource back to empty string or null

### ISSUE THREAD

**Issue by alexeyatbluescape** [env0/terraform-provider-env0#719]
**Describe the bug**
I have bunch of environments, and I wanted to disable speculative pr plans and automated deployments are off.

So I have reverted `run_plan_on_pull_requests` to false, but got this error:
`Error: [{0 run_plan_on_pull_requests or deploy_on_push must be enabled for auto_deploy_by_custom_glob  []}]`

Setting `run_plan_on_pull_requests` to null worked, but now every terraform run I see the following change that does not go away:

``` # module.environment["xxx"].env0_environment.main will be updated in-place
  ~ resource "env0_environment" "main" {
      - auto_deploy_by_custom_glob       = "+((somepath/tel/**)|(somepath/tel/**))" -> null
        id                               = "9d6602e4-f94a-4b9d-bfa6-6143863f582c"
        name                             = "xxx"
        # (11 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

I cant even set that property in environment web UI to empty string.

**To Reproduce**
On environment resource set:
- auto_deploy_by_custom_glob to some glob
- run_plan_on_pull_requests to `true`
- auto_deploy_on_path_changes_only to `true`

`apply`

On environment resource set:
- auto_deploy_by_custom_glob to `""` or `null`
- run_plan_on_pull_requests to `false`
- auto_deploy_on_path_changes_only to `false`

`apply`
`apply`

**Expected behavior**
Last apply should have no changes

**Acutual behavior**
Last apply keeps showing change on `auto_deploy_by_custom_glob` property

**Provider Version**
1.15.1

**Screenshots**

**Additional context**
Workaround: when I want to disable `run_plan_on_pull_requests`, I will keep it on, but will set glob pattern to something that does not exist.
This will still show bunch of github actions on PR, but they should be in the skipped state.

**Comment by alexeyatbluescape** [comment]
Not sure why this got closed because of another PR reference in our private repo...

**Comment by TomerHeber** [comment]
[v1.15.2](https://github.com/env0/terraform-provider-env0/tree/v1.15.2) was released.

**Comment by TomerHeber** [comment]
@alexeyatbluescape - silly question, but have you removed `auto_deploy_by_custom_glob` from the terraform?

**Comment by alexeyatbluescape** [comment]
No, it's conditional on a speculative plan flag. It's either string with path or ""\null

**Comment by alexeyatbluescape** [comment]
@TomerHeber sorry for late reply, but I have created a demo with the issue:

https://github.com/alexeyatbluescape/tf-test/tree/test/environment-test

Instructions on this line:
https://github.com/alexeyatbluescape/tf-test/blob/test/environment-test/vars.auto.tfvars.example#L5

**Comment by TomerHeber** [comment]
@alexeyatbluescape - thank you!
A fix has already been deployed. Let me know if you are still encountering issues.

**Comment by alexeyatbluescape** [comment]
Thanks again @TomerHeber @away168. I was able to implement PR plans feature switch successfully now with latest provider version! Now subsequent terraform runs stay clean.
