### ISSUE TITLE
Add "Budget exceeded" event name to env0_notification_project_assignment resource

### ISSUE THREAD

**Issue by armantur** [env0/terraform-provider-env0#731]
**Is your feature request related to a problem? Please describe.**

I'm not able to configure "Budget exceeded" event notification via env0 provider. I can do it only via env0 web console.

**Describe the solution you'd like**

It would be nice to add "budgetExceeded" event name to env0_notification_project_assignment resource.

**Describe alternatives you've considered**

I don't think there is any alternative exists since we planning to manage hundreds of env0 projects using Terraform and enabling notifications manually would be exhaustingю

**Comment by project-kmac** [comment]
@TomerHeber, this is already in the API - as https://docs.env0.com/reference/notifications-update-project-notification-settings as `budgetExceeded`
