### ISSUE TITLE
Changing values in Azure Cost Credentials results in a 409 error

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#734]
**Describe the bug**
```
│ Error: 409 Conflict: Credentials named azure_cost_credential already exist for organization bde19c6d-d0dc-4b11-a951-8f43fe49db92
│ 
│   with env0_azure_cost_credentials.default,
│   on main.tf line 14, in resource "env0_azure_cost_credentials" "default":
│   14: resource "env0_azure_cost_credentials" "default" {
│ 
```
**To Reproduce**

1. Deploy an "Azure Cost Credential" (see file example below)
2. modify a value in the cost credential (for example - tenant_id) 
3. Re-Deploy Azure Cost Credential - approve plan.
4. get error.

**Expected behavior**

Cost Credential should update without errors.

**Provider Version**
v1.15.5

**Screenshots**
![CleanShot 2023-10-23 at 15 11 14](https://github.com/env0/terraform-provider-env0/assets/2107354/a5994697-0dd9-41a4-a2f7-3bbe93d7505d)

**Additional context**
Sample Code:

main.tf

```
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
    }
  }
}

# Configure the env0 provider

provider "env0" {
}

resource "env0_azure_cost_credentials" "default" {
  client_id       = "test"
  client_secret   = "test"
  name            = "azure_cost_credential"
  subscription_id = "test"
  tenant_id       = "test2"
}

```

**Comment by TomerHeber** [comment]
I suspect there's an issue with the API call, not the provider.
Will update once I have more information.

**Comment by avnerenv0** [comment]
yeah it's on the API side, we'll handle it

**Comment by Wassap124** [comment]
working on it, will update when im done

**Comment by Wassap124** [comment]
Hey, just updating that the fix rolled out, and the backend should take the name into account if it's the current name

**Comment by TomerHeber** [comment]
@Wassap124 - with your permission may I close this issue?

**Comment by Wassap124** [comment]
sounds good to me
