### ISSUE TITLE
Add new OIDC credentials creation and assigment

### ISSUE THREAD

**Issue by Yossi-kerner** [env0/terraform-provider-env0#743]
As part of the built-in OIDC authentication epic we added 4 new deployment credentials types that we will need to support in the provider. The new credentials are:
* AWS OIDC:
  - `name` - (String) the name for the credential
  - `arn` - (String) the aws role arn
  - `duration` - (Number, optional) the session duration in seconds. If set must be one of the following: 3600 (1h), 7200 (2h), 14400 (4h), 18000 (5h default), 28800 (8h), 43200 (12h)
* GCP OIDC:
  - `name` - (String) the name for the credential
  - `jwt_configuration_file_content` - (String) should contain the JSON content of the JWT configuration file
* Azure OIDC:
  - `name` - (String) the name for the credential
  - `subscription_id` - (String) the azure subscription id
  - `client_id` - (String) the azure client id
  - `tenant_id` - (String) the azure tenant id
* Vault OIDC:
  - `name` - (String) the name for the credential
  - `vault_addr` - (String) the vault instance address
  - `vault_version` - (String) the vault version to download
  - `vault_role` - (String) the vault role
  -  `jwt_auth_backend_path` - (String) the JWT authentication method path
  - `vault_namespace` - (String, optional) the vault namespace

Currently, when adding an AWS credential, in env0 we have the `externalId` field. For the new credentials we won't need that we will need `JWT OIDC sub`. For example the input form for GCP OIDC credential looks like this:

![image](https://github.com/env0/terraform-provider-env0/assets/72043585/c230245d-812c-435d-b0c9-fb308ca8f0e8)

You can get that value from our API `<base-url>/api-keys/oidc-sub?organizationId=<org-id>`

We will also need to be able to assign all those new credentials to projects

**Comment by TomerHeber** [comment]
@Yossi-kerner where is the documentation in https://docs.env0.com/reference/ ?

**Comment by TomerHeber** [comment]
@Yossi-kerner - another question: should it be a new resource(s)?

**Comment by Yossi-kerner** [comment]
> @Yossi-kerner where is the documentation in https://docs.env0.com/reference/ ?

It's not a documented API but the url with the auth header should be enough

> @Yossi-kerner - another question: should it be a new resource(s)?

If I understand correctly from the provider docs the current credentials are their own resources so these should be too

Let me know if you have more questions 🙏
