### ISSUE TITLE
cannot see terraform variables for workflow using "env0_configuration_variable"

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#757]
**Describe the bug**
When creating a `env0_configuraiton_variable` type=terraform on the workflow environment ID, the variable will not show up in the UI.

**To Reproduce**

```
terraform {
  required_providers {
    env0 = {
      source  = "env0/env0"
      version = "1.16.0"
    }
  }
}

provider "env0" {
  organization_id = "bde19c6d-d0dc-4b11-a951-8f43fe49db92"
}

resource "env0_environment" "workflow" {
  name                             = "workflow test nov28"
  project_id                       = "6932f811-a7d0-4c8e-923c-3f2f285dacc3"
  template_id                      = "448f65cc-562d-48fc-bf49-f99da850bc2c"
  run_plan_on_pull_requests        = false
  deploy_on_push                   = false
  auto_deploy_on_path_changes_only = false
  revision                         = "main"
  force_destroy                    = true
  approve_plan_automatically       = true
  is_inactive                      = false

  # sub_environment_configuration {
  #   alias    = "b"
  #   revision = "main"

  #   configuration {
  #     name  = "b"
  #     value = "b specific nov28"
  #   }
  # }
}

resource "env0_configuration_variable" "a" {
  name           = "a"
  type           = "terraform"
  value          = "nov 28"
  environment_id = env0_environment.workflow.id
}

resource "env0_configuration_variable" "b" {
  name           = "b"
  type           = "environment"
  value          = "nov 28 b"
  environment_id = env0_environment.workflow.id
}

```

**Expected behavior**

env0 should overwrite the terraform variable for the sub_environment

**Provider Version**
1.16.0

**Screenshots**
![CleanShot 2023-11-28 at 13 49 26](https://github.com/env0/terraform-provider-env0/assets/2107354/fc2f5d58-c1ec-4066-b9b5-00b4d21368cb)

**Additional context**

**Comment by TomerHeber** [comment]
@away168 why did you remove the sub_environment_configuration ?
I don't think env0_configuration_variable `env0_environment.workflow.id` is supported.

**Comment by away168** [comment]
@TomerHeber wanted an alternative option of specifying a configuration variable for ALL sub-environments.  It "half" works when embedding into the env_environment resource.

**Comment by TomerHeber** [comment]
@away168 

My point is - I don' think the following is supported.
```
resource "env0_configuration_variable" "a" {
  name           = "a"
  type           = "terraform"
  value          = "nov 28"
  environment_id = env0_environment.workflow.id
}

resource "env0_configuration_variable" "b" {
  name           = "b"
  type           = "environment"
  value          = "nov 28 b"
  environment_id = env0_environment.workflow.id
}
```
Instead it should be done via `sub_environment_configuration`.
It's not working when you embed it to the "main" environment?

**Comment by away168** [comment]
> It's not working when you embed it to the "main" environment?
we (the customer) have not tried `sub_environment_configuration` because the intention is to create an configuration variable for the entire workflow, not just for one sub_environment.

>  I don' think the following is supported.
I mean it works when running terraform apply, and it is recorded into the env0 Backend.
So I'm not sure at what level you mean it's not supported.
