### ISSUE TITLE
env0_environment resource allows you to bypass "required" terraform variables

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#758]
**Describe the bug**
when using `env0_environment` resource with a required terraform variable in a workflow sub_environment

**To Reproduce**
Create a template with a variable marked as required.
Use the template in a workfllow
Create the workflow environment using env0_environment resource

**Expected behavior**
env0_environment should now allow a deployment.

**Provider Version**
1.16.0

**Screenshots**

![CleanShot 2023-11-28 at 13 53 45](https://github.com/env0/terraform-provider-env0/assets/2107354/77ca1314-9874-4986-ae12-8cf0df69c15b)

![CleanShot 2023-11-28 at 13 54 16](https://github.com/env0/terraform-provider-env0/assets/2107354/bad7d8cf-b521-42c1-8f81-a117d352af04)

**Additional context**

https://app.env0.com/p/6932f811-a7d0-4c8e-923c-3f2f285dacc3/environments/697b277a-95ca-425b-a42a-0fb984c67d00?tabname=deployment-logs

**Comment by TomerHeber** [comment]
@away168 - wouldn't this be an issue with API/product itself?
Could you describe in more detail what the provider is doing wrong? maybe a small sample?

Thank you!

**Comment by away168** [comment]
possibly an API / product issue - I don't really know. 

The UI - will prevent the deployment because it sees a required variable.
So I guess it's being caught before the backend call.  Need someone from RnD to help confirm.

**Comment by yaronya** [comment]
@away168 this is indeed not an issue with the TF provider. If it's still relevant - please open a ticket to the backend team 🙏
