### ISSUE TITLE
FR: env0 should return 400 when trying to update template ID inside env0_environment resource

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#766]
**Is your feature request related to a problem? Please describe.**
in the env0 UI, it is actually not possible to update the template associated with an environment
the template id is immutable. 

in the terraform provider - the provider will destroy and create the environment when the template id changes. 
this is considered a side effect (IMO)

**Describe the solution you'd like**
 
 instead we should return a 400 or error that this is not allowed.
 
**Describe alternatives you've considered**
"Using a  replace_triggered_by should ensure that users won't encounter this error"

**Additional context**
n/a

**Comment by TomerHeber** [comment]
@away168 - this is how terraform works.
Why is this not desired?

Would in "real-life" if you want to change the template id for an environment, you would delete it and create a new one?

**Comment by away168** [comment]
yeah, its how terraform works, but not really now env0 works. 
in env0 you cannot go to an enviroment and change the template. 

so an unsuspecting user - who is not familiar with env0 - and expects the template to get changed, will suddenly see their environment get destroyed, and create a new one.

environments getting destroyed is not ideal.

instead, in "real-life" the user should "mark as inactive" the existing env0 environment - and then create a new environment from the new template (with the same configuration).
