### ISSUE TITLE
Agents data source is returning a list of all agents in the organizations and ignores agent key

### ISSUE THREAD

**Issue by roni-frantchi** [env0/terraform-provider-env0#800]
**Describe the bug**
1. The [`agents` data source example](https://registry.terraform.io/providers/env0/env0/latest/docs/data-sources/agents) seems to be referencing a different data source - `agent_values`.  
2. That too however, seems off - as it [calls](https://github.com/env0/terraform-provider-env0/blob/main/env0/data_agents.go#L37) an [API](https://github.com/env0/terraform-provider-env0/blob/main/client/agent.go#L7-L20) which does nothing with `agent_key`, and returns a list of all agent on the organization.

**DoD**
1. The `data "env0_agents"` data source should not have an `agent_key` as it ignores it anyways and lists all in the organization
2. There should be a `data "env0_agent"` (singular, not plural) data source that _should_ get `agent_key` and return a **single** agent
3. The examples of both should be added/corrected

**Comment by TomerHeber** [comment]
@roni-frantchi I'm assuming this is now resolved.
Closing. Let me know if there are any additional action items.
