### ISSUE TITLE
Terraform Variables and Env Variables not created when adding prevent_auto_deploy true

### ISSUE THREAD

**Issue by zi-abrand** [env0/terraform-provider-env0#810]
**Describe the bug**
While adding the flag prevent_auto_deploy = true to the environment configuration all the other "configuration" bits are being ignored and env vars and tf vars are not created

**To Reproduce**
Steps to reproduce the behavior.
create an "env0_environment" resource and add the flag "prevent_auto_deploy = true"
apply it to create env and see tf vars and env vars not created

**Expected behavior**
env vars and tf vars appear in the new environment 

**Provider Version**
1.17.0

**Screenshots**
**example code:**
`resource "env0_environment" "test-namespace-stg" {
  name                       = "test-namespace-stg"
  project_id                 = data.env0_project.migration_dest.id
  workspace                  = "test-namespace-stg"
  approve_plan_automatically = false
  is_remote_backend          = true
  without_template_settings {
    repository           = "https://somerepo.com/test"
    path                 = "stg/"
    revision             = "master"
    type                 = "terraform"
    is_github_enterprise = true
    terraform_version    = "1.1.3"
  }

  configuration {
    name         = "eks_cluster"
    value        = "primary"
    is_sensitive = false
    type         = "terraform"
  }

  configuration {
    name         = "eks_namespace"
    value        = "test"
    is_sensitive = false
    type         = "terraform"
  }
}`

**Comment by yaronya** [comment]
Hi @zi-abrand 
Thanks for reporting the bug!
This has to do with a recent change. We'll prioritize a fix that will be out soon 🙏

**Comment by xjhofernandes** [comment]
Hello! Same here! :) 

When I try to create a environment with **prevent_auto_deploy** **true**, the environment created don't get the terraform variables that I pass. 

I'll be waiting for the fix too. 

Thanks, @yaronya.

**Comment by TomerHeber** [comment]
Hi @zi-abrand

A fix was applied. Is it now working as expected?
