### ISSUE TITLE
Refactor for Project Role assignments for Team #807

### ISSUE THREAD

**Issue by razbensimon** [env0/terraform-provider-env0#817]
The same as we did 
1. [here](https://github.com/env0/terraform-provider-env0/pull/813) for Organization Level assignments (team only).
2. [here](https://github.com/env0/terraform-provider-env0/pull/668) for Environment Level assignments (team + user).

We want to achieve the same for the new **Project** level **Team** assignments API.

We already implemented this but we now have synced our project team level to the new API too.
meaning we deprecating the old APIs, so we need to adjust the old resources related to Project<-->Team role assignments.

**deprecated APIs:**
1. [updateAssignments](https://docs.env0.com/reference/teams-update-assignments) 
2. [deleteSingleAssignment](https://docs.env0.com/reference/teams-delete-single-assignment) 
3. [createOrUpdateSingleAssignment](https://docs.env0.com/reference/teams-create-or-update-single-assignment) 
4. [getAssignments](https://docs.env0.com/reference/teams-get-assignments)

**new API:**
Use the new Team Role [APIs](https://docs.env0.com/reference/roles-get-team-role-assignments): Get, Upsert, Delete.
Same API as before, we just add `projectId`.
![image](https://github.com/env0/terraform-provider-env0/assets/5955905/45f18e92-9d56-4407-9fff-107b9e8df193)

**Comment by razbensimon** [comment]
cc @sagydr @yarivg

**Comment by TomerHeber** [comment]
Feature is released. I'm keeping it open because I still want to make additional refactoring.
