### ISSUE TITLE
Cloudformation Template - Forcing refresh of a TerraformVersion field

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#818]
**Describe the bug**
User is using a cloudformation template. 
and updated the provider to the latest version 1.17.2
and now the plan is showing that a "terraformVersion" is being replaced with a default value instead of keeping "" (empty string).
This is causing runs on a lot of unnecessary deployments to get triggered.

**To Reproduce**
Setup a cloudformation environment using older version of provider
update provider and rerun 

**Expected behavior**
No default value for terraformVersion

**Provider Version**
1.17.2

**Screenshots**
![CleanShot 2024-04-03 at 08 51 25](https://github.com/env0/terraform-provider-env0/assets/2107354/a803c5bc-698f-4a10-91ad-41c55f99556e)

**Comment by TomerHeber** [comment]
@away168 - what was the previous version?

**Comment by away168** [comment]
> @away168 - what was the previous version?

version = "1.16.1" 

(but even when reverting back they still the same issue... so 🤷 )

**Comment by TomerHeber** [comment]
> > @away168 - what was the previous version?
> 
> version = "1.16.1"
> 
> (but even when reverting back they still the same issue... so 🤷 )

@away168 - yeah it's probably a backend issue. I did create a PR to mitigate it. But waiting for it to be approved.
