### ISSUE TITLE
delete custom flows & approval policies when they are unassigned

### ISSUE THREAD

**Issue by alonnoga** [env0/terraform-provider-env0#824]
**Is your feature request related to a problem? Please describe.**
We recently added the ability to assign multiple custom flows / approval policies
We changed it so unassigned policies / custom flows don't even appear in the UI
So there is no separate way to delete them ( other than via api )

We'd prefer not leaving custom flows / approval policies that are not assigned to anything

**Describe the solution you'd like**
When a custom flow / approval policy is unassigned, attempt to delete it
If its also assigned to another scope you'll receive a BadRequest error ( so its safe to just try and delete it )

**Comment by TomerHeber** [comment]
Set to blocked until https://github.com/env0/terraform-provider-env0/issues/822 is resolved.

**Comment by TomerHeber** [comment]
Hi @alonnoga ,

This is against terraform design.
Assignment cannot be done if you do not create (or import) a custom flow/approval policy.
In other words, it's safe to assume that these resources will be in the terraform file.
They will be deleted once removed from the terraform file.

If we attempt to delete them, but are still listed in the terraform file, a "drift" will accour asking the user to approve their recreation.

Please let me know if I'm missing anything. Happy to discuss more.

**Comment by alonnoga** [comment]
When the resource is removed from tf is fine 👍🏻
Closing the issue
