### ISSUE TITLE
Configuration Variable in Workflow does not get "saved" in the state

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#838]
**Describe the bug**
The state does not "save" the configuration variable for a workflow environment 

**To Reproduce**
same setup as this https://github.com/env0/terraform-provider-env0/issues/831
gist: 
using tf provider - create environment (workflow) - with prevent_auto_deploy=true
and configuration variable.

1. initial deployment shows all resources will get created.
![CleanShot 2024-04-26 at 15 46 34](https://github.com/env0/terraform-provider-env0/assets/2107354/e8f08dc8-d8b2-493c-94b7-a9e9deff0d8e)

2. On re-deployment - configuration variable changes are being suggested in the plan.
![CleanShot 2024-04-26 at 15 48 06](https://github.com/env0/terraform-provider-env0/assets/2107354/69a39251-e436-4a95-ac9e-2e37411caef5)

**Expected behavior**
Redploy should show no changes requrired.

**Provider Version**
1.18.3

**Screenshots**
in-line

**Additional context**
Note: The configuration (that needs to be "created" again) has actually been saved in the workflow... see image below. this is the image of the variables - before the redeployment.
![CleanShot 2024-04-26 at 15 52 53](https://github.com/env0/terraform-provider-env0/assets/2107354/03fb585c-dcbf-4b75-95e2-fec893f6af33)

* on 3rd deployment - the configuration is finally synced with the state.

**Comment by TomerHeber** [comment]
Applied a mitigation. Closing this for now.

**Comment by away168** [comment]
the plan always shows a drift, but the configuration is updated.
