### ISSUE TITLE
Fix HTTP client retry mechanism

### ISSUE THREAD

**Issue by yaronya** [env0/terraform-provider-env0#877]
We recently experienced flakiness in the `029_provider` harness test where consecutive call to get the recently created provider fails (see `test_provider_data` data resource that was commented out in #876)

I explicitly tried to search for the log of `Received a failed or not found response, retrying request` as specified [here](https://github.com/env0/terraform-provider-env0/blob/04b33955336c2c7b791910d5689580a5f857dbe1/env0/provider.go#L210-L210) but couldn't find it in the log - meaning that it might not work

We should fix it and validate that it indeed works. We could validate it with:
1. Manually create a provider (or any other resource) @ env0
2. Manually remove it 
3. Configure a data resource against it - and see whether http client retries or not (with validating that the actual log is printed)

Please note to undo the changes of #876 too.

**Comment by TomerHeber** [comment]
@yaronya 

Generally retry will occur if INTEGRATION_TESTS environment variable is set to 1. 
Is that the case?
