### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by tomer-landesman** [env0/terraform-provider-env0#881]
**Describe the bug**
some tests are flaky, mainly around async triggering of deployments. the scenario we witnessed is:
1. environment is created
2. environment is destroyed
3. environment is created again (via trigger or schedule) 
4. project is failed to destroy because an environment is active

the tests:
`013_downstream_environments`
`014_environment_scheduling`

for `014_environment_scheduling`: 
the re-trigger is not initiated via the second apply, but by the schedule. we can increase dramatically the schedule cron to not happen before the project is destroyed

for `013_downstream_environments`:
we can add logic to skip the second apply so the downstream won't trigger again before the destroy is called

**To Reproduce**
hard to manually reproduce. we saw it on bors.

**Expected behavior**
those tests should be more reliable 

**Provider Version**
E.g.: 1.14.15

**Screenshots**

**Additional context**

**Comment by TomerHeber** [comment]
This is now fixed by adding a force destroy to the projects.
