### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by razbensimon** [env0/terraform-provider-env0#90]
We need some run this as pre-commit git hook on this repo
1. `go fmt` (`husky` & `prettier` style)

Considering those too (maybe with a different hook? commit can be slow)
2. generate mocks
3. generate docs

**Comment by yaronya** [comment]
I think 2 + 3 should be done in CI/Release rather than locally.
See also #57

**Comment by yaronya** [comment]
Will be done in #262
