### ISSUE TITLE
removing `agent_project_assignment` does not auto re-assign to the default agent

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#914]
**Describe the bug**
when using `agent_project_assignment` to assign a project to a specific agent, and then removing the `agent_project_assignment` resource, the project is not properly re-assigned to the default agent.

**To Reproduce**
* have org with at least 2 agents.
* use `agent_project_assignment` to assign project to 2nd agent (non-default)
* remove `agent_project_assignment`
* see project assignment - still stuck on 2nd agent.

**Expected behavior**
* after removing `agent_project_assignment` project should use default agent.

**Provider Version**
1.19.7

**Screenshots**
![CleanShot 2024-07-30 at 09 16 59](https://github.com/user-attachments/assets/e83ccfc7-86a6-473f-a146-1440bd61c317)

**Additional context**

**Comment by TomerHeber** [comment]
This is being discussed in Slack. The current API vs terraform schema, may cause undesired race conditions.
May need to depracate this resource.
