### ISSUE TITLE
resource cloud_configuration 

### ISSUE THREAD

**Issue by GiliFaroEnv0** [env0/terraform-provider-env0#922]
Please add resource to manage Cloud configuration for insights 
[Create API ](https://docs.env0.com/reference/cloud-resources-service-create-cloud-configuration)
[Get by Id API](https://docs.env0.com/reference/cloud-resources-service-find-cloud-configuration-by-id)
[Update API](https://docs.env0.com/reference/cloud-resources-service-update-cloud-configuration)
[Delete API](https://docs.env0.com/reference/cloud-resources-service-delete-cloud-configuration)

the schema should contain the following fields:

- `name` : string
- `provider` : enum , currently only AWS exist but in the neer future we will add more cloud providers (GCP/AZURE)
- `configuration`: according to the provider
- - AWS configuration:
- - - `accountId` -string 
- - -  `bucketName` -string
- - -  `regions` - string[], array of all the regions, if you can add a close list of all the AWS regions it will be great but don't over invest
- - - `prefix` - string (optional) 
- `health` - boolean (CALCULATED) , indicate if the configuration is valid and we get scan the cloud account

**Comment by HeverFarber** [comment]
I don't think `health` is part of the schema. the user has nothing to do with health
