### ISSUE TITLE
Stop requiring `gitlab_project_id` for `gitlab` templates

### ISSUE THREAD

**Issue by Wassap124** [env0/terraform-provider-env0#940]
**Is your feature request related to a problem? Please describe.**
We require users to fill in the gitlab project id.

however - a gitlab repo and a gitlab project have a 1 to 1 relation, hence this is redundant.

**Describe the solution you'd like**
No longer let the users insert the field.

**Describe alternatives you've considered**
possibly keep it as optional, but that's really not needed

**Comment by yaronya** [comment]
Please note - the BE behavior is still in development and this shouldn't be implemented yet on the provider. @Wassap124 will update once it's done.
