### ISSUE TITLE
approve_plan_automatically attribute fails for sub_environment

### ISSUE THREAD

**Issue by asafsb** [env0/terraform-provider-env0#947]
**Describe the bug**
When adding `approve_plan_automatically` attribute to a sub_environment, using either `true` or `false` values, a failure occurs with the following error:

```
│ Error: could not create environment: 400 Bad Request: approval flow can't be enabled on workflow environments
│ 
│   with env0_environment.example_with_hcl_configuration,
│   on main.tf line 15, in resource "env0_environment" "example_with_hcl_configuration":
│   15: resource "env0_environment" "example_with_hcl_configuration" {
│ 
```

**To Reproduce**
1. Create an `env0_environment` resource with `sub_environment_configuration`
2. Add `approve_plan_automatically` attribute to one of the sub environments
3. Run apply

```
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
    }
  }
}

provider "env0" {
  api_key    = var.env0_api_key
  api_secret = var.env0_api_secret
}

resource "env0_environment" "example_with_hcl_configuration" {
  name        = "test workflow approval policy"
  project_id  = var.project_id
  template_id = var.template_id

  is_remote_backend = "true"


  sub_environment_configuration {
    alias    = "vpc"
    revision = "main"
    approve_plan_automatically = "true"
  }

    sub_environment_configuration {
    alias    = "eks"
    revision = "main"
    approve_plan_automatically = "true"
  }
}
```

**Expected behavior**
Automatic approval plan should be enabled/disabled on the sub environment, as per the documentation:
[https://registry.terraform.io/providers/env0/env0/latest/docs/resources/environment#nested-schema-for-sub_environment_configuration](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/environment#nested-schema-for-sub_environment_configuration)

**Provider Version**
latest (1.20.6) and 1.19.3

**Screenshots**
![CleanShot 2024-09-03 at 17 33 48@2x](https://github.com/user-attachments/assets/60c5028d-c8cf-42e7-ae8f-523b6376bf0b)

**Comment by TomerHeber** [comment]
Blocking this ticket since it's a backend issue.

**Comment by TomerHeber** [comment]
hi @weinguy-env0 

Unfortunatly, the backend treats `UserRequiresApproval` as a tri-boolean (this isn't the only field that has this problem):
1. undefined.
2. true.
3. false.

Ideally, the backend shouldn't have tri-booleans, as this causes alot of confusion (E.g. this issue). But I guess it is what it is.

If I understand you correctly, you would want `UserRequiresApproval` to be explicitly `false` or `true` instead of `undefined` for workflow templates?

**Comment by weinguy-env0** [comment]
yeah tri-boolean can be really confusing, I see how this can be missed easily.
For workflow templates, we would want `UserRequiresApproval` to always be `false` for the environment. If it isn't we will throw an error.
If we can we should make it transparent for the user.
