### ISSUE TITLE
Unit tests take a minute

### ISSUE THREAD

**Issue by avnerenv0** [env0/terraform-provider-env0#96]
On Mac :

```
ok  	github.com/env0/terraform-provider-env0/client/http	(cached)
=== RUN   TestUnitOrganizationData
--- PASS: TestUnitOrganizationData (16.59s)
=== RUN   TestUnitProjectData
--- PASS: TestUnitProjectData (16.04s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestMissingConfigurations
--- PASS: TestMissingConfigurations (0.00s)
=== RUN   TestUnitProjectResource
--- PASS: TestUnitProjectResource (27.87s)
PASS
ok  	github.com/env0/terraform-provider-env0/env0	61.365s
```

<div><img src="https://media4.giphy.com/media/bWM2eWYfN3r20/giphy.gif?cid=5a38a5a243a45uohk6cyvu3w8b05k4a4iijtl91tsmh9oook&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/gifs/aint-nobody-got-time-for-that-gif-bWM2eWYfN3r20">GIPHY</a></div>

**Comment by yaronya** [comment]
@avnerenv0 it's a known issue with using terraform provider tests FYI 😞

**Comment by avnerenv0** [comment]
@yaronya is there a GH issue for that or something?

**Comment by yaronya** [comment]
Nope, but found a thread about it on reddit and everyone complained there 🤷 

Whoever takes it - you can try parallelizing the tests using `resource.ParallelTest`, which currently fails as it seems tests override each others mocks (that shouldn't really happen as each test initializes a unique mock controller so 🤔 )
