### ISSUE TITLE
resource `env0_environment` - add support to change `template_id`

### ISSUE THREAD

**Issue by asafsb** [env0/terraform-provider-env0#986]
**Is your feature request related to a problem? Please describe.**
Support the new feature to redeploy an environment using a new template:
![image](https://github.com/user-attachments/assets/e7b86637-4669-4918-95db-4c94a04a2eed)

Currently changing the `template_id` value of an existing environment fails with the following error:
![CleanShot 2024-12-05 at 22 50 25@2x](https://github.com/user-attachments/assets/24f72036-5c46-4b6a-bb89-ea7be0213600)

**Describe the solution you'd like**
Allow changing `template_id` after an environment was already created

**Additional context**
Tested that the matching API call to works:
```
curl --request POST \                                                                                                                                                     
     --url https://api.env0.com/environments/<environment-id>/deployments \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "blueprintRevision": "main",
  "blueprintId": "<new-template-id>"
}

**Comment by lkanerv** [comment]
I can confirm that this is resolved. Mahalo!
